/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Secante;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author yaser
 */
public class ReglaSecanteJava extends javax.swing.JFrame {

    static String valorC, valor1, valor2, valor3, valor4, valor5, valor6, int1, int2, error, deci;
    static double GradoC = 0.0, Grado1 = 0.0, Grado2, Grado3, Grado4, Grado5, Grado6 = 0.0, ErrorI;
    static double fxa, fxb, xr, xrn, xrnv, xrv, xa, xb, Inter1 = 0.0, Inter2 = 0.0, Inter2v = 0.0, comp, XRNV, XRN, err;
    static double grad, min, seg, grad2, min2, seg2;
    static double radtime1, radtime2;
    static String Grad = "", Min = "", Seg = "", Grad2 = "", Min2 = "", Seg2 = "";
    static int Decimal, count = 0;
    static double xc = 0.0, xcn = 0.0, xcv = 0.0;

    public ReglaSecanteJava() {
        initComponents();

        txtGrado1.setText("0");
        txtGrado2.setText("0");
        txtGrado3.setText("0");
        txtGrado4.setText("0");
        txtGrado5.setText("0");
        txtGrado6.setText("0");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt3 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt8 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtGrado2 = new javax.swing.JTextField();
        txtConstante = new javax.swing.JTextField();
        txtGrado1 = new javax.swing.JTextField();
        txtGrado3 = new javax.swing.JTextField();
        txtGrado4 = new javax.swing.JTextField();
        txtGrado5 = new javax.swing.JTextField();
        txtGrado6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIntervalo1 = new javax.swing.JTextField();
        txtIntervalo2 = new javax.swing.JTextField();
        txtError = new javax.swing.JTextField();
        txtDecimales = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("1");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("REGLA DE LA SECANTE");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("1");

        txtGrado2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGrado2KeyReleased(evt);
            }
        });

        txtConstante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConstanteKeyReleased(evt);
            }
        });

        txtGrado1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGrado1KeyReleased(evt);
            }
        });

        txtGrado3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGrado3KeyReleased(evt);
            }
        });

        txtGrado4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGrado4KeyReleased(evt);
            }
        });

        txtGrado5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGrado5KeyReleased(evt);
            }
        });

        txtGrado6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGrado6KeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Constante");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("2");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("3");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("4");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("5");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("6");

        txtIntervalo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIntervalo1KeyReleased(evt);
            }
        });

        txtIntervalo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIntervalo2KeyReleased(evt);
            }
        });

        txtError.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtErrorKeyReleased(evt);
            }
        });

        txtDecimales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDecimalesKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Intervalo 1");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Intervalo 2");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Error");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Decimales");

        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtConstante, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(27, 27, 27)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGrado1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(39, 39, 39)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel4)
                                        .addGap(104, 104, 104)
                                        .addComponent(jLabel7)
                                        .addGap(100, 100, 100)
                                        .addComponent(jLabel8)
                                        .addGap(103, 103, 103)
                                        .addComponent(jLabel9)
                                        .addGap(101, 101, 101)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtGrado2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtGrado3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtGrado4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel14)
                                                .addComponent(txtDecimales, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(txtGrado5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtGrado6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                                                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtIntervalo1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))
                                        .addGap(48, 48, 48)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtIntervalo2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12))
                                        .addGap(52, 52, 52)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGrado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConstante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGrado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGrado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGrado4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGrado5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGrado6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIntervalo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIntervalo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDecimales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        valorC = txtConstante.getText();
        valor1 = txtGrado1.getText();
        valor2 = txtGrado2.getText();
        valor3 = txtGrado3.getText();
        valor4 = txtGrado4.getText();
        valor5 = txtGrado5.getText();
        valor6 = txtGrado6.getText();
        int1 = txtIntervalo1.getText();//intervalos 1
        int2 = txtIntervalo2.getText();//intervalos 2
        error = txtError.getText();
        deci = txtDecimales.getText();
        //string to double grados
        GradoC = Double.parseDouble(valorC);//constante
        Grado1 = Double.parseDouble(valor1);//grado 1
        Grado2 = Double.parseDouble(valor2);//grado 2
        Grado3 = Double.parseDouble(valor3);//grado 3
        Grado4 = Double.parseDouble(valor4);//grado 4
        Grado5 = Double.parseDouble(valor5);//grado 5

        count = 0;
        error = txtError.getText();
        deci = txtDecimales.getText();

        //ERROR
        ErrorI = Double.parseDouble(error);//Error digitado
        //Decimales
        Decimal = Integer.parseInt(deci);
        //  Intervals de xa y xb ya convertidos a double
        Inter1 = Double.parseDouble(int1);
        Inter2 = Double.parseDouble(int2);

        if (txtConstante.getText().isEmpty()
                || txtGrado1.getText().isEmpty()
                || txtGrado2.getText().isEmpty()
                || txtGrado3.getText().isEmpty()
                || txtGrado4.getText().isEmpty()
                || txtGrado5.getText().isEmpty()
                || txtGrado6.getText().isEmpty()
                || txtError.getText().isEmpty()
                || txtDecimales.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "CAMPOS VACIOS", "INFORMACION", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //Hacemos llamar la regla de la secante. 
        Rsecante();


    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtConstanteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConstanteKeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,10})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtConstante.getText());
        if (match.find()) {
            txtGrado1.setEnabled(true);
            txtGrado2.setEnabled(true);
            txtGrado3.setEnabled(true);
            txtGrado4.setEnabled(true);
            txtGrado5.setEnabled(true);
            txtGrado6.setEnabled(true);
            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtGrado1.setEnabled(false);
            txtGrado2.setEnabled(false);
            txtGrado3.setEnabled(false);
            txtGrado4.setEnabled(false);
            txtGrado5.setEnabled(false);
            txtGrado6.setEnabled(false);
            btnCalcular.setEnabled(false);
            return;
        }


    }//GEN-LAST:event_txtConstanteKeyReleased

    private void txtGrado1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado1KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,10})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtGrado1.getText());
        if (match.find()) {
            txtGrado2.setEnabled(true);
            txtGrado3.setEnabled(true);
            txtGrado4.setEnabled(true);
            txtGrado5.setEnabled(true);
            txtGrado6.setEnabled(true);
            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtGrado2.setEnabled(false);
            txtGrado3.setEnabled(false);
            txtGrado4.setEnabled(false);
            txtGrado5.setEnabled(false);
            txtGrado6.setEnabled(false);
            btnCalcular.setEnabled(false);
            return;
        }


    }//GEN-LAST:event_txtGrado1KeyReleased

    private void txtGrado2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado2KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,10})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtGrado2.getText());
        if (match.find()) {

            txtGrado3.setEnabled(true);
            txtGrado4.setEnabled(true);
            txtGrado5.setEnabled(true);
            txtGrado6.setEnabled(true);
            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);

            txtGrado3.setEnabled(false);
            txtGrado4.setEnabled(false);
            txtGrado5.setEnabled(false);
            txtGrado6.setEnabled(false);
            btnCalcular.setEnabled(false);
            return;
        }

    }//GEN-LAST:event_txtGrado2KeyReleased

    private void txtGrado3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado3KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,10})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtGrado3.getText());
        if (match.find()) {

            txtGrado4.setEnabled(true);
            txtGrado5.setEnabled(true);
            txtGrado6.setEnabled(true);
            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);

            txtGrado4.setEnabled(false);
            txtGrado5.setEnabled(false);
            txtGrado6.setEnabled(false);
            btnCalcular.setEnabled(false);
            return;
        }


    }//GEN-LAST:event_txtGrado3KeyReleased

    private void txtGrado4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado4KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,10})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtGrado4.getText());
        if (match.find()) {

            txtGrado5.setEnabled(true);
            txtGrado6.setEnabled(true);
            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);

            txtGrado5.setEnabled(false);
            txtGrado6.setEnabled(false);
            btnCalcular.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_txtGrado4KeyReleased

    private void txtGrado5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado5KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,10})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtGrado5.getText());
        if (match.find()) {

            txtGrado6.setEnabled(true);
            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);

            txtGrado6.setEnabled(false);
            btnCalcular.setEnabled(false);
            return;
        }

    }//GEN-LAST:event_txtGrado5KeyReleased

    private void txtGrado6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado6KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,10})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtGrado6.getText());
        if (match.find()) {

            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);

            btnCalcular.setEnabled(false);
            return;
        }

    }//GEN-LAST:event_txtGrado6KeyReleased

    private void txtIntervalo1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIntervalo1KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,10})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtIntervalo1.getText());
        if (match.find()) {

            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);

            btnCalcular.setEnabled(false);
            return;
        }

    }//GEN-LAST:event_txtIntervalo1KeyReleased

    private void txtIntervalo2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIntervalo2KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,10})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtIntervalo2.getText());
        if (match.find()) {

            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);

            btnCalcular.setEnabled(false);
            return;
        }

    }//GEN-LAST:event_txtIntervalo2KeyReleased

    private void txtErrorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtErrorKeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,10})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtError.getText());
        if (match.find()) {

            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);

            btnCalcular.setEnabled(false);
            return;
        }


    }//GEN-LAST:event_txtErrorKeyReleased


    private void txtDecimalesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDecimalesKeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,10})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtDecimales.getText());
        if (match.find()) {

            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);

            btnCalcular.setEnabled(false);
            return;
        }


    }//GEN-LAST:event_txtDecimalesKeyReleased
    public void Rsecante() {
        //1 / cos= a la secante 

        // xa y xb son los valores que se ingresan
        /*System.out.println("xa : " + Inter1);//-4
        System.out.println("xb : " + Inter2);//2
        //paso 1
        fxa = (Grado6 * (Math.pow(Inter1, 6)) + Grado5 * (Math.pow(Inter1, 5)) + Grado4 * (Math.pow(Inter1, 4)) + Grado3 * (Math.pow(Inter1, 3)) + Grado2 * (Math.pow(Inter1, 2)) + Grado1 * (Math.pow(Inter1, 1)) + GradoC);
        System.out.println("fxa : " + String.format("%." + Decimal + "f", fxa));
        // -6
        fxb = ((Grado6 * (Math.pow(Inter2, 6))) + (Grado5 * (Math.pow(Inter2, 5))) + (Grado4 * (Math.pow(Inter2, 4))) + (Grado3 * (Math.pow(Inter2, 3))) + (Grado2 * (Math.pow(Inter2, 2))) + ((Grado1 * (Math.pow(Inter2, 1)))) + GradoC);
        System.out.println("fxb : " + String.format("%." + Decimal + "f", fxb));*/
        // 12
        //primera salida if ==0 
        /**
         * condition si el result es cero so nos imprime una alerta que ya se
         * encotro la raiz de la aproximacion
         */
        /*if (fxa == 0) {//**************
            JOptionPane.showMessageDialog(null, "Se encontro la raiz de fxa", "FELICIDADES", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("El valor es: " + Inter1 + " Su RAIZ: " + String.format("%." + Decimal + "f", fxa));
            return;
        } else if (fxb == 0) {
            JOptionPane.showMessageDialog(null, "Se encontro la raiz de fxB", "FELICIDADES", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("El valor es: " + Inter2 + " Su RAIZ: " + String.format("%." + Decimal + "f", fxb));
            return;
        }//-**********************/
        //usamos la formula iterativa.
        do {
            count++;
            System.out.println("---ITERADOR---" + count);
            //INTERVALOS
            System.out.println("xa : " + Inter1);//-4
            System.out.println("xb : " + Inter2);// 2
            //Intervalo2v se inicializa con inter2 
            Inter2v = Inter2;// se mantine Inter 2 -> 2

            //paso 1
            fxa = (Grado6 * (Math.pow(Inter1, 6)) + Grado5 * (Math.pow(Inter1, 5)) + Grado4 * (Math.pow(Inter1, 4)) + Grado3 * (Math.pow(Inter1, 3)) + Grado2 * (Math.pow(Inter1, 2)) + Grado1 * (Math.pow(Inter1, 1)) + GradoC);
            System.out.println("fxa : " + String.format("%." + Decimal + "f", fxa));
            // -6
            fxb = ((Grado6 * (Math.pow(Inter2, 6))) + (Grado5 * (Math.pow(Inter2, 5))) + (Grado4 * (Math.pow(Inter2, 4))) + (Grado3 * (Math.pow(Inter2, 3))) + (Grado2 * (Math.pow(Inter2, 2))) + ((Grado1 * (Math.pow(Inter2, 1)))) + GradoC);
            System.out.println("fxb : " + String.format("%." + Decimal + "f", fxb));
            //Comprobacion si el erro es igual a cero: Primera salida. 12

            if (fxa == 0) {//**************
                JOptionPane.showMessageDialog(null, "Se encontro la raiz de fxa", "FELICIDADES", JOptionPane.INFORMATION_MESSAGE);
                System.out.println("El valor es: " + Inter1 + " Su RAIZ: " + String.format("%." + Decimal + "f", fxa));
                return;
            } else if (fxb == 0) {
                JOptionPane.showMessageDialog(null, "Se encontro la raiz de fxB", "FELICIDADES", JOptionPane.INFORMATION_MESSAGE);
                System.out.println("El valor es: " + Inter2 + " Su RAIZ: " + String.format("%." + Decimal + "f", fxb));
                return;
            }

            //sacamos la aproximacion del numero hacia la raiz
            xcn = Inter2 - (fxb * (Inter2 - Inter1)) / (fxb - fxa);
            System.out.println("Aprox Raiz: " + xcn);//-0.4, 

            err = Math.abs(((xcn - Inter2) / xcn) * 100);
            System.out.println("Error: " + err);

            if (err <= ErrorI) {
                System.out.println("SE ENCONTRO EL ERROR: " + err);
                return;
            } else {
                //se haran los recorridos hacia los nuevos valores PARA TENER NUEVOS INTERVALOS DONDE EJECUTAR DE NUEVO TODO EL PROGRAMA.

                //inter2= -2
                Inter2 = xcn;
                //System.out.println("Inter2 cambio: "+Inter2);
                Inter1 = Inter2v;
                //System.out.println("Intervalo viejo en inter1: "+Inter1);

            }
        } while (count <= 100);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReglaSecanteJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReglaSecanteJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReglaSecanteJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReglaSecanteJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReglaSecanteJava().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtConstante;
    private javax.swing.JTextField txtDecimales;
    private javax.swing.JTextField txtError;
    private javax.swing.JTextField txtGrado1;
    private javax.swing.JTextField txtGrado2;
    private javax.swing.JTextField txtGrado3;
    private javax.swing.JTextField txtGrado4;
    private javax.swing.JTextField txtGrado5;
    private javax.swing.JTextField txtGrado6;
    private javax.swing.JTextField txtIntervalo1;
    private javax.swing.JTextField txtIntervalo2;
    // End of variables declaration//GEN-END:variables
}
