/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trigonometricas;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import java.lang.*;

/**
 *
 * @author 52333
 */
public class GradoRadian extends javax.swing.JFrame {

    /**
     * Creates new form GradoRadian
     */
    public GradoRadian() {
        initComponents();
        this.setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnGRadGrad = new javax.swing.ButtonGroup();
        jMenu3 = new javax.swing.JMenu();
        JpPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbtnRadianes = new javax.swing.JRadioButton();
        rbtnGrados = new javax.swing.JRadioButton();
        rbtnReglaSecate = new javax.swing.JRadioButton();
        rbtnGNewtonR = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuRadianes = new javax.swing.JMenuItem();
        mnuGrados = new javax.swing.JMenuItem();
        mnureglasecante = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));

        JpPrincipal.setMaximumSize(new java.awt.Dimension(650, 500));
        JpPrincipal.setMinimumSize(new java.awt.Dimension(650, 500));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("¿CON QUE LE GUSTARIA TRABAJAR?");

        rbtnGRadGrad.add(rbtnRadianes);
        rbtnRadianes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rbtnRadianes.setText("Radianes");
        rbtnRadianes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRadianesActionPerformed(evt);
            }
        });

        rbtnGRadGrad.add(rbtnGrados);
        rbtnGrados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rbtnGrados.setText("Grados");
        rbtnGrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnGradosActionPerformed(evt);
            }
        });

        rbtnGRadGrad.add(rbtnReglaSecate);
        rbtnReglaSecate.setText("Regla Secante");
        rbtnReglaSecate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnReglaSecateActionPerformed(evt);
            }
        });

        rbtnGRadGrad.add(rbtnGNewtonR);
        rbtnGNewtonR.setText("Newton-Raphson");
        rbtnGNewtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnGNewtonRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpPrincipalLayout = new javax.swing.GroupLayout(JpPrincipal);
        JpPrincipal.setLayout(JpPrincipalLayout);
        JpPrincipalLayout.setHorizontalGroup(
            JpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpPrincipalLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(rbtnGNewtonR, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbtnRadianes)
                .addGap(18, 18, 18)
                .addComponent(rbtnGrados, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbtnReglaSecate, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(JpPrincipalLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JpPrincipalLayout.setVerticalGroup(
            JpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpPrincipalLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(JpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnRadianes)
                    .addComponent(rbtnGrados)
                    .addComponent(rbtnReglaSecate)
                    .addComponent(rbtnGNewtonR))
                .addContainerGap(318, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu.png"))); // NOI18N
        jMenu1.setText("Menu");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        mnuRadianes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuRadianes.setText("Radianes");
        mnuRadianes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRadianesActionPerformed(evt);
            }
        });
        jMenu1.add(mnuRadianes);

        mnuGrados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuGrados.setText("Grados");
        mnuGrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGradosActionPerformed(evt);
            }
        });
        jMenu1.add(mnuGrados);

        mnureglasecante.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnureglasecante.setText("Regla Secante");
        mnureglasecante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnureglasecanteActionPerformed(evt);
            }
        });
        jMenu1.add(mnureglasecante);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Informacion");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void rbtnGradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnGradosActionPerformed
        // TODO add your handling code here:
        GradosT grado = new GradosT();
        Paneles(grado);
        
    }//GEN-LAST:event_rbtnGradosActionPerformed

    private void mnuRadianesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRadianesActionPerformed
        // TODO add your handling code here:
        RadianesT radianes = new RadianesT();
        Paneles(radianes);
    }//GEN-LAST:event_mnuRadianesActionPerformed

    private void rbtnRadianesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRadianesActionPerformed
        // TODO add your handling code here:
        RadianesT radianes = new RadianesT();
        Paneles(radianes);

    }//GEN-LAST:event_rbtnRadianesActionPerformed

    private void mnuGradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGradosActionPerformed
        // TODO add your handling code here:
        GradosT grado = new GradosT();
        Paneles(grado);

    }//GEN-LAST:event_mnuGradosActionPerformed

    private void rbtnReglaSecateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnReglaSecateActionPerformed
        // TODO add your handling code here:
        //direccinamiento de los la regla de la secante
        ReglaSecante gls=new ReglaSecante();
        Paneles(gls);
        
    }//GEN-LAST:event_rbtnReglaSecateActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        //menu  de regla de la secante
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void mnureglasecanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnureglasecanteActionPerformed
        // TODO add your handling code here:
        ReglaSecante rgs=new ReglaSecante();
        Paneles(rgs);
    }//GEN-LAST:event_mnureglasecanteActionPerformed

    private void rbtnGNewtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnGNewtonRActionPerformed
        // TODO add your handling code here:
        NewtonRaphson nr=new NewtonRaphson();
        Paneles(nr);
    }//GEN-LAST:event_rbtnGNewtonRActionPerformed

    public void Paneles(JPanel p) {
        p.setSize(650, 500);
        p.setLocation(0, 0);
        
        JpPrincipal.removeAll();
        JpPrincipal.add(p, BorderLayout.CENTER);
        JpPrincipal.revalidate();
        JpPrincipal.repaint();

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradoRadian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradoRadian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradoRadian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradoRadian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradoRadian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuGrados;
    private javax.swing.JMenuItem mnuRadianes;
    private javax.swing.JMenuItem mnureglasecante;
    private javax.swing.JRadioButton rbtnGNewtonR;
    private javax.swing.ButtonGroup rbtnGRadGrad;
    private javax.swing.JRadioButton rbtnGrados;
    private javax.swing.JRadioButton rbtnRadianes;
    private javax.swing.JRadioButton rbtnReglaSecate;
    // End of variables declaration//GEN-END:variables
}
