package trigonometricas;

import static trigonometricas.GradosT.Decimal;
import static trigonometricas.GradosT.Inter1;
import static trigonometricas.GradosT.err;
import static trigonometricas.GradosT.fxa;
import static trigonometricas.GradosT.xrn;
import java.awt.BorderLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import static trigonometricas.NewtonRaphson.Decimal;
import static trigonometricas.NewtonRaphson.ErrorI;
import static trigonometricas.NewtonRaphson.Grado1;
import static trigonometricas.NewtonRaphson.Grado2;
import static trigonometricas.NewtonRaphson.Grado3;
import static trigonometricas.NewtonRaphson.Grado4;
import static trigonometricas.NewtonRaphson.Grado5;
import static trigonometricas.NewtonRaphson.Grado6;
import static trigonometricas.NewtonRaphson.GradoC;
import static trigonometricas.NewtonRaphson.Inter1;
import static trigonometricas.NewtonRaphson.XRN;
import static trigonometricas.NewtonRaphson.count;
import static trigonometricas.NewtonRaphson.deci;
import static trigonometricas.NewtonRaphson.err;
import static trigonometricas.NewtonRaphson.error;
import static trigonometricas.NewtonRaphson.fxa;
import static trigonometricas.NewtonRaphson.fxb;
import static trigonometricas.NewtonRaphson.int1;
import static trigonometricas.NewtonRaphson.valor1;
import static trigonometricas.NewtonRaphson.valor2;
import static trigonometricas.NewtonRaphson.valor3;
import static trigonometricas.NewtonRaphson.valor4;
import static trigonometricas.NewtonRaphson.valor5;
import static trigonometricas.NewtonRaphson.valor6;
import static trigonometricas.NewtonRaphson.valorC;
/**
 *
 * @author DrunkedOwly
 */
public class NewtonRamsonware extends javax.swing.JFrame {
        static double GradoC = 0.0, Grado1 = 0.0, Grado2, Grado3, Grado4, Grado5, Grado6 = 0.0, ErrorI;
    static double fxa, fxb, xr, xrn, xrnv, xrv, xa, xb, Inter1 = 0.0, Inter2 = 0.0, Inter2v = 0.0, comp, XRNV, XRN, err;
    static double grad, min, seg, grad2, min2, seg2;
    static double radtime1, radtime2;
    static String Grad = "", Min = "", Seg = "", Grad2 = "", Min2 = "", Seg2 = "";
    static int Decimal, count = 0;
    static double xc = 0.0, xcn = 0.0, xcv = 0.0;
    
    /**
     * Creates new form NewtonRamsonware
     */
    public NewtonRamsonware() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGrado1 = new javax.swing.JTextField();
        txtGrado2 = new javax.swing.JTextField();
        txtGrado3 = new javax.swing.JTextField();
        txtGrado4 = new javax.swing.JTextField();
        txtGrado5 = new javax.swing.JTextField();
        txtGrado6 = new javax.swing.JTextField();
        txtConstante = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        txtInter1 = new javax.swing.JTextField();
        txtError = new javax.swing.JTextField();
        txtDecimales = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        lblConstante = new javax.swing.JLabel();
        lblGrado1 = new javax.swing.JLabel();
        lblGrado2 = new javax.swing.JLabel();
        lblGrado3 = new javax.swing.JLabel();
        lblGrado4 = new javax.swing.JLabel();
        lblGrado5 = new javax.swing.JLabel();
        lblGrado6 = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        lblDecimales1 = new javax.swing.JLabel();
        lblIntervalo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Newton Raphson");
        setMaximumSize(new java.awt.Dimension(650, 400));
        setMinimumSize(new java.awt.Dimension(650, 400));
        setPreferredSize(new java.awt.Dimension(650, 400));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGrado1KeyReleased(evt);
            }
        });
        getContentPane().setLayout(null);

        txtGrado1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGrado1KeyTyped(evt);
            }
        });
        getContentPane().add(txtGrado1);
        txtGrado1.setBounds(110, 60, 71, 30);

        txtGrado2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGrado2KeyTyped(evt);
            }
        });
        getContentPane().add(txtGrado2);
        txtGrado2.setBounds(190, 60, 71, 30);

        txtGrado3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGrado3KeyTyped(evt);
            }
        });
        getContentPane().add(txtGrado3);
        txtGrado3.setBounds(280, 60, 71, 30);

        txtGrado4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGrado4KeyTyped(evt);
            }
        });
        getContentPane().add(txtGrado4);
        txtGrado4.setBounds(360, 60, 71, 30);

        txtGrado5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGrado5KeyTyped(evt);
            }
        });
        getContentPane().add(txtGrado5);
        txtGrado5.setBounds(450, 60, 71, 30);

        txtGrado6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGrado6KeyTyped(evt);
            }
        });
        getContentPane().add(txtGrado6);
        txtGrado6.setBounds(530, 60, 71, 30);

        txtConstante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConstanteKeyTyped(evt);
            }
        });
        getContentPane().add(txtConstante);
        txtConstante.setBounds(30, 60, 71, 30);

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 100, 230, 240);

        txtInter1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInter1KeyTyped(evt);
            }
        });
        getContentPane().add(txtInter1);
        txtInter1.setBounds(460, 140, 60, 30);

        txtError.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtErrorKeyTyped(evt);
            }
        });
        getContentPane().add(txtError);
        txtError.setBounds(290, 140, 64, 30);

        txtDecimales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDecimalesKeyTyped(evt);
            }
        });
        getContentPane().add(txtDecimales);
        txtDecimales.setBounds(370, 140, 64, 30);

        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(350, 230, 110, 50);

        lblConstante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConstante.setText("Constante");
        lblConstante.setMinimumSize(new java.awt.Dimension(63, 16));
        lblConstante.setPreferredSize(new java.awt.Dimension(63, 16));
        getContentPane().add(lblConstante);
        lblConstante.setBounds(40, 40, 55, 16);

        lblGrado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGrado1.setText("1°Grado");
        lblGrado1.setMinimumSize(new java.awt.Dimension(63, 16));
        lblGrado1.setPreferredSize(new java.awt.Dimension(63, 16));
        getContentPane().add(lblGrado1);
        lblGrado1.setBounds(120, 40, 55, 16);

        lblGrado2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGrado2.setText("2°Grado");
        lblGrado2.setMinimumSize(new java.awt.Dimension(63, 16));
        lblGrado2.setPreferredSize(new java.awt.Dimension(63, 16));
        getContentPane().add(lblGrado2);
        lblGrado2.setBounds(200, 40, 55, 16);

        lblGrado3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGrado3.setText("3°Grado");
        lblGrado3.setMinimumSize(new java.awt.Dimension(63, 16));
        lblGrado3.setPreferredSize(new java.awt.Dimension(63, 16));
        getContentPane().add(lblGrado3);
        lblGrado3.setBounds(290, 40, 55, 16);

        lblGrado4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGrado4.setText("4°Grado");
        lblGrado4.setMinimumSize(new java.awt.Dimension(63, 16));
        lblGrado4.setPreferredSize(new java.awt.Dimension(63, 16));
        getContentPane().add(lblGrado4);
        lblGrado4.setBounds(370, 40, 55, 16);

        lblGrado5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGrado5.setText("5°Grado");
        lblGrado5.setMinimumSize(new java.awt.Dimension(63, 16));
        lblGrado5.setPreferredSize(new java.awt.Dimension(63, 16));
        getContentPane().add(lblGrado5);
        lblGrado5.setBounds(460, 40, 55, 16);

        lblGrado6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGrado6.setText("6°Grado");
        lblGrado6.setMinimumSize(new java.awt.Dimension(63, 16));
        lblGrado6.setPreferredSize(new java.awt.Dimension(63, 16));
        getContentPane().add(lblGrado6);
        lblGrado6.setBounds(540, 40, 55, 16);

        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblError.setText("Error deseado");
        lblError.setMaximumSize(new java.awt.Dimension(55, 22));
        lblError.setMinimumSize(new java.awt.Dimension(55, 22));
        lblError.setName(""); // NOI18N
        getContentPane().add(lblError);
        lblError.setBounds(280, 100, 75, 22);

        lblDecimales1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDecimales1.setText("N°Decimales");
        lblDecimales1.setMaximumSize(new java.awt.Dimension(55, 22));
        lblDecimales1.setMinimumSize(new java.awt.Dimension(55, 22));
        lblDecimales1.setName(""); // NOI18N
        getContentPane().add(lblDecimales1);
        lblDecimales1.setBounds(370, 100, 75, 22);

        lblIntervalo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIntervalo1.setText("Intervalo 1");
        lblIntervalo1.setToolTipText("");
        getContentPane().add(lblIntervalo1);
        lblIntervalo1.setBounds(460, 110, 80, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGrado1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado1KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,10})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtGrado1.getText());
        if (match.find()) {
            txtGrado2.setEnabled(true);
            txtGrado3.setEnabled(true);
            txtGrado4.setEnabled(true);
            txtGrado5.setEnabled(true);
            txtGrado6.setEnabled(true);
            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtGrado2.setEnabled(false);
            txtGrado3.setEnabled(false);
            txtGrado4.setEnabled(false);
            txtGrado5.setEnabled(false);
            txtGrado6.setEnabled(false);
            btnCalcular.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_txtGrado1KeyReleased

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        valorC = txtConstante.getText();
        valor1 = txtGrado1.getText();
        valor2 = txtGrado2.getText();
        valor3 = txtGrado3.getText();
        valor4 = txtGrado4.getText();
        valor5 = txtGrado5.getText();
        valor6 = txtGrado6.getText();
        int1 = txtInter1.getText();//intervalos 1
        //int2 = txtInter2.getText();//intervalos 2
        error = txtError.getText();
        deci = txtDecimales.getText();
        //string to double grados
        GradoC = Double.parseDouble(valorC);//constante
        Grado1 = Double.parseDouble(valor1);//grado 1
        Grado2 = Double.parseDouble(valor2);//grado 2
        Grado3 = Double.parseDouble(valor3);//grado 3
        Grado4 = Double.parseDouble(valor4);//grado 4
        Grado5 = Double.parseDouble(valor5);//grado 5
        Grado6 = Double.parseDouble(valor6);//grado 6

        count = 0;
        error = txtError.getText();
        deci = txtDecimales.getText();

        //ERROR
        ErrorI = Double.parseDouble(error);//Error digitado
        //Decimales
        Decimal = Integer.parseInt(deci);
        //  Intervals de xa y xb ya convertidos a double
        Inter1 = Double.parseDouble(int1);
        //Inter2 = Double.parseDouble(int2);

        if (txtConstante.getText().isEmpty()
            || txtGrado1.getText().isEmpty()
            || txtGrado2.getText().isEmpty()
            || txtGrado3.getText().isEmpty()
            || txtGrado4.getText().isEmpty()
            || txtGrado5.getText().isEmpty()
            || txtGrado6.getText().isEmpty()
            || txtError.getText().isEmpty()
            || txtDecimales.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "CAMPOS VACIOS", "INFORMACION", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //Hacemos llamar la regla de la secante.
        NewtonR();
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtConstanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConstanteKeyTyped
        digito(evt);
    }//GEN-LAST:event_txtConstanteKeyTyped

    private void txtGrado1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado1KeyTyped
        digito(evt);
    }//GEN-LAST:event_txtGrado1KeyTyped

    private void txtGrado2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado2KeyTyped
        digito(evt);
    }//GEN-LAST:event_txtGrado2KeyTyped

    private void txtGrado3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado3KeyTyped
        digito(evt);
    }//GEN-LAST:event_txtGrado3KeyTyped

    private void txtGrado4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado4KeyTyped
        digito(evt);
    }//GEN-LAST:event_txtGrado4KeyTyped

    private void txtGrado5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado5KeyTyped
        digito(evt);
    }//GEN-LAST:event_txtGrado5KeyTyped

    private void txtGrado6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado6KeyTyped
        digito(evt);
    }//GEN-LAST:event_txtGrado6KeyTyped

    private void txtInter1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInter1KeyTyped
        digito(evt);
    }//GEN-LAST:event_txtInter1KeyTyped

    private void txtErrorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtErrorKeyTyped
        digito(evt);
    }//GEN-LAST:event_txtErrorKeyTyped

    private void txtDecimalesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDecimalesKeyTyped
        digito(evt);
    }//GEN-LAST:event_txtDecimalesKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewtonRamsonware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewtonRamsonware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewtonRamsonware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewtonRamsonware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewtonRamsonware().setVisible(true);
            }
        });
    }
    
    
    public static void digito(java.awt.event.KeyEvent evt)
    {
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) && c!='.' && c!='-')
        {
            evt.consume();
        }
    }
    
    
//Secante
    public void NewtonR() {
        double fxav=0.0;
        do {
            count++;
            System.out.println("---ITERADOR---" + count);
            
            //paso 1
            fxa = (Grado6 * (Math.pow(Inter1, 6)) + Grado5 * (Math.pow(Inter1, 5)) + Grado4 * (Math.pow(Inter1, 4)) + Grado3 * (Math.pow(Inter1, 3)) + Grado2 * (Math.pow(Inter1, 2)) + Grado1 * (Math.pow(Inter1, 1)) + GradoC);
            System.out.println("fxa : " + String.format("%." + Decimal + "f", fxa));// 32.5
            fxav=fxa;
            
            // obtenemos la derivada. 
            double g6=Grado6 * 6;
            System.out.println("6: "+g6);
            double g5= Grado5 * 5;
            System.out.println("5: "+g5);
            Grado5=g6;
            double g4= Grado4 * 4;
            System.out.println("4: "+g4);
            Grado4=g5;
            double g3=Grado3 * 3;
            System.out.println("3: "+g3);
            Grado3=g4;
            double g2=Grado2 * 2;
            System.out.println("5: "+g2);
            Grado2=g3;
            System.out.println("g2: "+Grado2);
            double g1=Grado1 * 1;
            Grado1=g2;
            System.out.println("g1: "+Grado1);
            GradoC=g1;
            System.out.println("Gc: "+GradoC);
            
            
            fxb = (Grado5 * (Math.pow(Inter1, 5)) + Grado4 * (Math.pow(Inter1, 4)) + Grado3 * (Math.pow(Inter1, 3)) + Grado2 * (Math.pow(Inter1, 2)) + Grado1 * (Math.pow(Inter1, 1)) + GradoC);
            System.out.println("Derivada : " + fxb);// 32.5
            
            
            //formula para la primera iteracion
            XRN=(Inter1)-(fxa/fxb);
            System.out.println("XRN: "+XRN);
            err = (Math.abs((XRN - Inter1) / XRN) * 100);
            System.out.println("Error: " + err);
            if(err <= ErrorI){
                System.out.println("Se encontro el error");
                return;
            }else{
                Inter1=XRN;
                valorC = txtConstante.getText();
                valor1 = txtGrado1.getText();
                valor2 = txtGrado2.getText();
                valor3 = txtGrado3.getText();
                valor4 = txtGrado4.getText();
                valor5 = txtGrado5.getText();
                valor6 = txtGrado6.getText();
                int1 = txtInter1.getText();//intervalos 1
                //int2 = txtInter2.getText();//intervalos 2
                error = txtError.getText();
                deci = txtDecimales.getText();
                //string to double grados
                GradoC = Double.parseDouble(valorC);//constante
                Grado1 = Double.parseDouble(valor1);//grado 1
                Grado2 = Double.parseDouble(valor2);//grado 2
                Grado3 = Double.parseDouble(valor3);//grado 3
                Grado4 = Double.parseDouble(valor4);//grado 4
                Grado5 = Double.parseDouble(valor5);//grado 5
                Grado6 = Double.parseDouble(valor6);//grado 6

            }
            
        } while (count <= 3);

    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConstante;
    private javax.swing.JLabel lblDecimales1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblGrado1;
    private javax.swing.JLabel lblGrado2;
    private javax.swing.JLabel lblGrado3;
    private javax.swing.JLabel lblGrado4;
    private javax.swing.JLabel lblGrado5;
    private javax.swing.JLabel lblGrado6;
    private javax.swing.JLabel lblIntervalo1;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtConstante;
    private javax.swing.JTextField txtDecimales;
    private javax.swing.JTextField txtError;
    private javax.swing.JTextField txtGrado1;
    private javax.swing.JTextField txtGrado2;
    private javax.swing.JTextField txtGrado3;
    private javax.swing.JTextField txtGrado4;
    private javax.swing.JTextField txtGrado5;
    private javax.swing.JTextField txtGrado6;
    private javax.swing.JTextField txtInter1;
    // End of variables declaration//GEN-END:variables
}
