/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package trigonometricas;

import static trigonometricas.GradosT.Grad;
import static trigonometricas.GradosT.Grad2;
import static trigonometricas.GradosT.Inter1;
import static trigonometricas.GradosT.Inter2;
import static trigonometricas.GradosT.Min;
import static trigonometricas.GradosT.Min2;
import static trigonometricas.GradosT.Seg;
import static trigonometricas.GradosT.Seg2;
import static trigonometricas.GradosT.grad;
import static trigonometricas.GradosT.grad2;
import static trigonometricas.GradosT.min;
import static trigonometricas.GradosT.min2;
import static trigonometricas.GradosT.radtime1;
import static trigonometricas.GradosT.radtime2;
import static trigonometricas.GradosT.seg;
import static trigonometricas.GradosT.seg2;
import java.awt.BorderLayout;
import java.lang.Math;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author 52333
 */
public class RadianesT extends javax.swing.JPanel {

    static String valorC, valor1, valor2, valor3, valor4, valor5, valor6, int1, int2, error, deci;
    static double GradoC = 0.0, Grado1 = 0.0, Grado2, Grado3, Grado4, Grado5, Grado6 = 0.0, ErrorI;
    static double fxa, fxb, xr, xrn, xrnv, xrv, xa, xb, Inter1 = 0.0, Inter2 = 0.0, comp, XRNV, XRN, err;
    static double grad, min, seg, grad2, min2, seg2;
    static double radtime1, radtime2;
    static String Grad = "", Min = "", Seg = "", Grad2 = "", Min2 = "", Seg2 = "";
    static int Decimal, count = 0;

    public RadianesT() {
        initComponents();
        //Intervalo 1
        jTextFieldNumerador1.setEnabled(false);
        jTextFieldNumerador2.setEnabled(false);

        //intervalo 2
        jTextFieldDenominador1.setEnabled(false);
        jTextFieldDenominador2.setEnabled(false);

        jTextFieldDenominador1.setText("0");
        jTextFieldDenominador2.setText("0");
        jTextFieldNumerador1.setText("0");
        jTextFieldNumerador2.setText("0");
        
        txtInter1.setText("0");
        txtInter2.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbxTrigonometricas = new javax.swing.JComboBox<>();
        txtGrado1 = new javax.swing.JTextField();
        txtGrado2 = new javax.swing.JTextField();
        txtGrado3 = new javax.swing.JTextField();
        txtGrado4 = new javax.swing.JTextField();
        txtGrado5 = new javax.swing.JTextField();
        txtGrado6 = new javax.swing.JTextField();
        txtConstante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        txtInter1 = new javax.swing.JTextField();
        txtInter2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtError = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDeciamales = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        chbxPiRad = new javax.swing.JCheckBox();
        jTextFieldNumerador1 = new javax.swing.JTextField();
        jTextFieldNumerador2 = new javax.swing.JTextField();
        jTextFieldDenominador1 = new javax.swing.JTextField();
        jTextFieldDenominador2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setMaximumSize(new java.awt.Dimension(650, 500));
        setMinimumSize(new java.awt.Dimension(650, 500));
        setPreferredSize(new java.awt.Dimension(650, 500));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("FUNCION RADIANES:");
        add(jLabel1);
        jLabel1.setBounds(40, 40, 220, 19);

        cmbxTrigonometricas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seno", "Coseno", "Tangente", "Contangente", "Secante", "Cosecante" }));
        add(cmbxTrigonometricas);
        cmbxTrigonometricas.setBounds(260, 40, 110, 22);

        txtGrado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrado1ActionPerformed(evt);
            }
        });
        txtGrado1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGrado1KeyReleased(evt);
            }
        });
        add(txtGrado1);
        txtGrado1.setBounds(110, 100, 71, 30);

        txtGrado2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGrado2KeyReleased(evt);
            }
        });
        add(txtGrado2);
        txtGrado2.setBounds(190, 100, 71, 30);

        txtGrado3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGrado3KeyReleased(evt);
            }
        });
        add(txtGrado3);
        txtGrado3.setBounds(280, 100, 71, 30);

        txtGrado4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGrado4KeyReleased(evt);
            }
        });
        add(txtGrado4);
        txtGrado4.setBounds(360, 100, 71, 30);

        txtGrado5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGrado5KeyReleased(evt);
            }
        });
        add(txtGrado5);
        txtGrado5.setBounds(450, 100, 71, 30);

        txtGrado6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrado6ActionPerformed(evt);
            }
        });
        txtGrado6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGrado6KeyReleased(evt);
            }
        });
        add(txtGrado6);
        txtGrado6.setBounds(530, 100, 71, 30);

        txtConstante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConstanteActionPerformed(evt);
            }
        });
        txtConstante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConstanteKeyReleased(evt);
            }
        });
        add(txtConstante);
        txtConstante.setBounds(30, 100, 71, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Constante");
        add(jLabel2);
        jLabel2.setBounds(40, 70, 70, 10);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("1");
        add(jLabel3);
        jLabel3.setBounds(140, 70, 20, 10);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("2");
        add(jLabel4);
        jLabel4.setBounds(230, 70, 8, 10);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("3");
        add(jLabel5);
        jLabel5.setBounds(310, 70, 8, 10);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("4");
        add(jLabel6);
        jLabel6.setBounds(400, 70, 8, 10);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("5");
        add(jLabel7);
        jLabel7.setBounds(480, 70, 8, 10);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("6");
        add(jLabel8);
        jLabel8.setBounds(560, 70, 8, 10);

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(100, 300, 270, 140);

        txtInter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInter1ActionPerformed(evt);
            }
        });
        txtInter1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInter1KeyReleased(evt);
            }
        });
        add(txtInter1);
        txtInter1.setBounds(450, 190, 60, 30);

        txtInter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInter2ActionPerformed(evt);
            }
        });
        txtInter2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInter2KeyReleased(evt);
            }
        });
        add(txtInter2);
        txtInter2.setBounds(550, 190, 60, 30);

        jLabel9.setText("Intervalo 1");
        add(jLabel9);
        jLabel9.setBounds(450, 170, 60, 16);

        jLabel10.setText("Intervalo 2");
        add(jLabel10);
        jLabel10.setBounds(550, 170, 60, 16);

        jLabel11.setText("Error");
        add(jLabel11);
        jLabel11.setBounds(450, 230, 40, 16);

        txtError.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtErrorKeyReleased(evt);
            }
        });
        add(txtError);
        txtError.setBounds(450, 250, 64, 30);

        jLabel12.setText("Deciamles");
        add(jLabel12);
        jLabel12.setBounds(550, 230, 60, 16);

        txtDeciamales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeciamalesActionPerformed(evt);
            }
        });
        txtDeciamales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDeciamalesKeyReleased(evt);
            }
        });
        add(txtDeciamales);
        txtDeciamales.setBounds(550, 250, 64, 30);

        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/plus.png"))); // NOI18N
        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        add(btnCalcular);
        btnCalcular.setBounds(500, 310, 110, 50);

        chbxPiRad.setText("Pi/Radianes");
        chbxPiRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbxPiRadActionPerformed(evt);
            }
        });
        add(chbxPiRad);
        chbxPiRad.setBounds(390, 40, 190, 20);

        jTextFieldNumerador1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNumerador1KeyReleased(evt);
            }
        });
        add(jTextFieldNumerador1);
        jTextFieldNumerador1.setBounds(130, 200, 71, 30);

        jTextFieldNumerador2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNumerador2KeyReleased(evt);
            }
        });
        add(jTextFieldNumerador2);
        jTextFieldNumerador2.setBounds(220, 200, 64, 30);

        jTextFieldDenominador1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDenominador1KeyReleased(evt);
            }
        });
        add(jTextFieldDenominador1);
        jTextFieldDenominador1.setBounds(130, 250, 71, 30);

        jTextFieldDenominador2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDenominador2KeyReleased(evt);
            }
        });
        add(jTextFieldDenominador2);
        jTextFieldDenominador2.setBounds(220, 250, 64, 30);

        jLabel13.setText("Intevalo 1");
        add(jLabel13);
        jLabel13.setBounds(130, 180, 60, 16);

        jLabel14.setText("Intervalo 2");
        add(jLabel14);
        jLabel14.setBounds(220, 180, 60, 16);
        add(jSeparator1);
        jSeparator1.setBounds(220, 240, 70, 10);
        add(jSeparator2);
        jSeparator2.setBounds(130, 240, 70, 10);
    }// </editor-fold>//GEN-END:initComponents

    private void txtConstanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConstanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConstanteActionPerformed

    private void txtInter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInter2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInter2ActionPerformed

    private void txtDeciamalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeciamalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeciamalesActionPerformed

    private void txtGrado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrado1ActionPerformed
        // TODO add your handling code here:
        //radian a grado
        /*double num1 = 90;
        double res = Math.toDegrees(num1);

        //grado a radian
        double num2 = 90;
        double res2 = Math.toRadians(num1);*/


    }//GEN-LAST:event_txtGrado1ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        valorC = txtConstante.getText();
        valor1 = txtGrado1.getText();
        valor2 = txtGrado2.getText();
        valor3 = txtGrado3.getText();
        valor4 = txtGrado4.getText();
        valor5 = txtGrado5.getText();
        valor6 = txtGrado6.getText();
        int1 = txtInter1.getText();//intervalos 1
        int2 = txtInter2.getText();//intervalos 2
        error = txtError.getText();
        deci = txtDeciamales.getText();
        //string to double grados
        GradoC = Double.parseDouble(valorC);//constante
        Grado1 = Double.parseDouble(valor1);//grado 1
        Grado2 = Double.parseDouble(valor2);//grado 2
        Grado3 = Double.parseDouble(valor3);//grado 3
        Grado4 = Double.parseDouble(valor4);//grado 4
        Grado5 = Double.parseDouble(valor5);//grado 5
        Inter1 = Double.parseDouble(int1);
        Inter2 = Double.parseDouble(int2);

        count = 0;
        error = txtError.getText();
        deci = txtDeciamales.getText();

        //ERROR
        ErrorI = Double.parseDouble(error);//Error digitado
        //Decimales
        Decimal = Integer.parseInt(deci);
        Inter1 = (Inter1);
        Inter2 = (Inter2);

        if (txtConstante.getText().isEmpty()
                || txtGrado1.getText().isEmpty()
                || txtGrado2.getText().isEmpty()
                || txtGrado3.getText().isEmpty()
                || txtGrado4.getText().isEmpty()
                || txtGrado5.getText().isEmpty()
                || txtGrado6.getText().isEmpty()
                || txtError.getText().isEmpty()
                || txtDeciamales.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "CAMPOS VACIOS", "INFORMACION", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (chbxPiRad.isSelected()) {

            String Num1 = jTextFieldNumerador1.getText();
            Double num1 = Double.parseDouble(Num1);

            String Den1 = jTextFieldDenominador1.getText();
            Double den1 = Double.parseDouble(Den1);
            Inter1 = (num1 * Math.PI) / den1;

            //-------------------------------------------------- Intervalo 2
            String Num2 = jTextFieldNumerador2.getText();
            Double num2 = Double.parseDouble(Num2);//variable a usar del inter1

            String Den2 = jTextFieldDenominador2.getText();
            Double den2 = Double.parseDouble(Den2);// variable a usar denominadorr del inter2
            Inter2 = (num2 * Math.PI) / den2;

        } else if (!chbxPiRad.isSelected()) {
            Inter1 = Math.toRadians(Inter1);
            Inter2 = Math.toRadians(Inter2);
        }

        switch (cmbxTrigonometricas.getSelectedIndex()) {
            case 0://seno
                Seno();
                break;
            case 1://Coseno
                Coseno();
                break;
            case 2: //Tangente

                Tangente();
                break;
            case 3://Contangente

                Contangente();
                break;
            case 4://Secante
                System.out.println("Secante");
                Secante();
                break;
            case 5://Cosecante
                System.out.println("Cosecante");
                Cosecante();
                break;
            default:
                JOptionPane.showMessageDialog(null, "FUERA DEL RANGO DE OPCIONES");

        }

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtConstanteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConstanteKeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,10})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtConstante.getText());
        if (match.find()) {
            txtGrado1.setEnabled(true);
            txtGrado2.setEnabled(true);
            txtGrado3.setEnabled(true);
            txtGrado4.setEnabled(true);
            txtGrado5.setEnabled(true);
            txtGrado6.setEnabled(true);
            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtGrado1.setEnabled(false);
            txtGrado2.setEnabled(false);
            txtGrado3.setEnabled(false);
            txtGrado4.setEnabled(false);
            txtGrado5.setEnabled(false);
            txtGrado6.setEnabled(false);
            btnCalcular.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_txtConstanteKeyReleased

    private void txtGrado1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado1KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,10})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtGrado1.getText());
        if (match.find()) {
            txtGrado2.setEnabled(true);
            txtGrado3.setEnabled(true);
            txtGrado4.setEnabled(true);
            txtGrado5.setEnabled(true);
            txtGrado6.setEnabled(true);
            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtGrado2.setEnabled(false);
            txtGrado3.setEnabled(false);
            txtGrado4.setEnabled(false);
            txtGrado5.setEnabled(false);
            txtGrado6.setEnabled(false);
            btnCalcular.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_txtGrado1KeyReleased

    private void txtGrado2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado2KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,10})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtGrado2.getText());
        if (match.find()) {

            txtGrado3.setEnabled(true);
            txtGrado4.setEnabled(true);
            txtGrado5.setEnabled(true);
            txtGrado6.setEnabled(true);
            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);

            txtGrado3.setEnabled(false);
            txtGrado4.setEnabled(false);
            txtGrado5.setEnabled(false);
            txtGrado6.setEnabled(false);
            btnCalcular.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_txtGrado2KeyReleased

    private void txtGrado3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado3KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,10})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtGrado3.getText());
        if (match.find()) {

            txtGrado4.setEnabled(true);
            txtGrado5.setEnabled(true);
            txtGrado6.setEnabled(true);
            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);

            txtGrado4.setEnabled(false);
            txtGrado5.setEnabled(false);
            txtGrado6.setEnabled(false);
            btnCalcular.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_txtGrado3KeyReleased

    private void txtGrado4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado4KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,10})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtGrado4.getText());
        if (match.find()) {

            txtGrado5.setEnabled(true);
            txtGrado6.setEnabled(true);
            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);

            txtGrado5.setEnabled(false);
            txtGrado6.setEnabled(false);
            btnCalcular.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_txtGrado4KeyReleased

    private void txtGrado5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado5KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,10})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtGrado5.getText());
        if (match.find()) {

            txtGrado6.setEnabled(true);
            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);

            txtGrado6.setEnabled(false);
            btnCalcular.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_txtGrado5KeyReleased

    private void txtGrado6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado6KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,10})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtGrado6.getText());
        if (match.find()) {

            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);

            btnCalcular.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_txtGrado6KeyReleased

    private void txtInter1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInter1KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,10})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtInter1.getText());
        if (match.find()) {

            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);

            btnCalcular.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_txtInter1KeyReleased

    private void txtInter2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInter2KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,10})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtInter2.getText());
        if (match.find()) {

            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);

            btnCalcular.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_txtInter2KeyReleased

    private void txtErrorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtErrorKeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,10})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtError.getText());
        if (match.find()) {

            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);

            btnCalcular.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_txtErrorKeyReleased

    private void txtDeciamalesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDeciamalesKeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,10})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(txtDeciamales.getText());
        if (match.find()) {

            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);

            btnCalcular.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_txtDeciamalesKeyReleased

    private void txtGrado6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrado6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrado6ActionPerformed

    private void chbxPiRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbxPiRadActionPerformed
        // TODO add your handling code here:
        if (chbxPiRad.isSelected()) {
            txtInter1.setEnabled(false);
            txtInter2.setEnabled(false);
            //Intervalo 1
            jTextFieldNumerador1.setEnabled(true);
            jTextFieldNumerador2.setEnabled(true);

            //intervalo 2
            jTextFieldDenominador1.setEnabled(true);
            jTextFieldDenominador2.setEnabled(true);

        } else if (!chbxPiRad.isSelected()) {

            txtInter1.setEnabled(true);
            txtInter2.setEnabled(true);

            //Intervalo 1
            jTextFieldNumerador1.setEnabled(false);
            jTextFieldNumerador2.setEnabled(false);

            //intervalo 2
            jTextFieldDenominador1.setEnabled(false);
            jTextFieldDenominador2.setEnabled(false);

        }
    }//GEN-LAST:event_chbxPiRadActionPerformed

    private void txtInter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInter1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInter1ActionPerformed

    private void jTextFieldNumerador1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumerador1KeyReleased
        // TODO add your handling code here:

        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,2})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(jTextFieldNumerador1.getText());
        if (match.find()) {

            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);

            btnCalcular.setEnabled(false);
            return;
        }

    }//GEN-LAST:event_jTextFieldNumerador1KeyReleased

    private void jTextFieldNumerador2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumerador2KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,2})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(jTextFieldNumerador2.getText());
        if (match.find()) {

            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);

            btnCalcular.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_jTextFieldNumerador2KeyReleased

    private void jTextFieldDenominador1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDenominador1KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,2})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(jTextFieldDenominador1.getText());
        if (match.find()) {

            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);

            btnCalcular.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_jTextFieldDenominador1KeyReleased

    private void jTextFieldDenominador2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDenominador2KeyReleased
        // TODO add your handling code here:
        String nombre = "^[-]?[0-9]{1,9}(?:\\.[0-9]{1,2})?$";
        Pattern patron = Pattern.compile(nombre);
        Matcher match = patron.matcher(jTextFieldDenominador2.getText());
        if (match.find()) {

            btnCalcular.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(this, "NO CARACTER ESPECIAL", "ERROR", JOptionPane.ERROR_MESSAGE);

            btnCalcular.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_jTextFieldDenominador2KeyReleased

    //seno
    public void Seno() {

        System.out.println("Inter1: " + Inter1);
        System.out.println("Inter2: " + Inter2);
        //paso 1
        fxa = Math.sin(Grado6 * (Math.pow(Inter1, 6)) + Grado5 * (Math.pow(Inter1, 5)) + Grado4 * (Math.pow(Inter1, 4)) + Grado3 * (Math.pow(Inter1, 3)) + Grado2 * (Math.pow(Inter1, 2)) + Grado1 * (Math.pow(Inter1, 1)) + GradoC);
        System.out.println("fxa : " + String.format("%." + Decimal + "f", fxa));

        fxb = Math.sin((Grado6 * (Math.pow(Inter2, 6))) + (Grado5 * (Math.pow(Inter2, 5))) + (Grado4 * (Math.pow(Inter2, 4))) + (Grado3 * (Math.pow(Inter2, 3))) + (Grado2 * (Math.pow(Inter2, 2))) + ((Grado1 * (Math.pow(Inter2, 1)))) + GradoC);
        System.out.println("fxb : " + String.format("%." + Decimal + "f", fxb));
        //paso 2
        if (fxa == 0) {//**************
            JOptionPane.showMessageDialog(null, "Se encontro la raiz de fxa", "FELICIDADES", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("El valor es: " + xa + " Su RAIZ: " + String.format("%." + Decimal + "f", fxa));
            return;
        } else if (fxb == 0) {
            JOptionPane.showMessageDialog(null, "Se encontro la raiz de fxB", "FELICIDADES", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("El valor es: " + xb + " Su RAIZ: " + String.format("%." + Decimal + "f", fxb));
            return;
        }//-*********************

        //paso 3
        comp = fxa * fxb;
        System.out.println("COMPARACION: " + comp);
        if (comp < 0) {

            //primera aproximscion de la raiz
            xr = (((fxa * Inter2) - (fxb * Inter1)) / (fxa - fxb));//aproximacion -0.083
            System.out.println("xr: " + xr);
            Inter1 = xr;
            do {
                count++;
                System.out.println("------CONTADOR-----: " + count);

                fxa = Math.sin((Grado6 * (Math.pow(Inter1, 6)) + Grado5 * (Math.pow(Inter1, 5)) + Grado4 * (Math.pow(Inter1, 4)) + Grado3 * (Math.pow(Inter1, 3)) + Grado2 * (Math.pow(Inter1, 2)) + Grado1 * (Math.pow(Inter1, 1)) + GradoC));
                System.out.println("fxa dentro de do: " + String.format("%." + Decimal + "f", fxa));//0
                XRNV = XRN;

                //se hace la formula iterativva XRN
                XRN = Inter2 - (((fxb * Inter1) - (fxb * Inter2)) / (fxa - fxb));
                System.out.println("APROXIMACION DE LA RAIZ: " + String.format("%." + Decimal + "f", XRN));//0

                //System.out.println("fxa: " + fxa);
                err = (Math.abs((XRN - XRNV) / XRN)) * 100;
                System.out.println("Error relativo: " + err);
                if (err <= ErrorI) {//ERROR DIGITADO
                    count++;
                    System.out.println("------CONTADOR-----:" + count);
                    System.out.println("APROXIMACION DE LA RAIZ: " + XRN);//0
                    System.out.println("tu error final es: " + err);
                    return;
                } else {
                    Inter1 = XRN;
                }
            } while (count <= 100);

        } else if (comp > 0) {
            JOptionPane.showMessageDialog(this, "NO ES EL INTERVALO CORRECTO. ¿DESEA CONTINUAR?", "UPS!", JOptionPane.YES_NO_OPTION);
            //se aplicara forzar el programa.
            fuerzaSeno();
            return;
        }

    }

    public void fuerzaSeno() {

        xr = (((fxa * Inter2) - (fxb * Inter1)) / (fxa - fxb));//aproximacion -0.083
        //System.out.println("xr: " + xr);
        do {
            count++;
            Inter1 = xr;//xr corresponde a xa(Inter1) y xa(Inter1) es el nuevo vslor.
            System.out.println("ITERADOR------" + count);
            System.out.println("fxa : " + fxa);
            System.out.println("fxb : " + fxb);
            System.out.println("Error : " + err);
            System.out.println("xr: " + xr);
            //System.out.println("xrn: " + xrn);
            //System.out.println("INTER1 XA: " + Inter1);
            //se sustuye en fxa con el nuevo valor xa

            fxa = Math.sin((Grado6 * (Math.pow(Inter1, 6)) + Grado5 * (Math.pow(Inter1, 5)) + Grado4 * (Math.pow(Inter1, 4)) + Grado3 * (Math.pow(Inter1, 3)) + Grado2 * (Math.pow(Inter1, 2)) + Grado1 * (Math.pow(Inter1, 1)) + GradoC));
            //System.out.println("fxaaaaaaaaaaaa" + fxa);
            fxb = Math.sin((Grado6 * (Math.pow(Inter2, 6))) + (Grado5 * (Math.pow(Inter2, 5))) + (Grado4 * (Math.pow(Inter2, 4))) + (Grado3 * (Math.pow(Inter2, 3))) + (Grado2 * (Math.pow(Inter2, 2))) + ((Grado1 * (Math.pow(Inter2, 1)))) + GradoC);
            xrn = Inter2 - ((fxb * Inter1) - (fxb * Inter2)) / (fxa - fxb);
            //195
            //xrnv = xrn;
            xr = (((fxa * Inter2) - (fxb * Inter1)) / (fxa - fxb));//aproximacion -0.083

            err = (Math.abs((xrn - Inter1) / xrn) * 100);

            if (err <= ErrorI) {
                System.out.println("Error Final: " + err);
                return;
            } else {
                //195
                Inter1 = xrn;
                //System.out.println("Inter1 cambio else: " + Inter1);
                //System.out.println("xrn cambio else: " + xrn);
            }
        } while (count < 100);

    }
    
    //coseno
    public void Coseno() {

        System.out.println("Inter1: " + Inter1);
        System.out.println("Inter2: " + Inter2);
        //paso 1
        fxa = Math.cos(Grado6 * (Math.pow(Inter1, 6)) + Grado5 * (Math.pow(Inter1, 5)) + Grado4 * (Math.pow(Inter1, 4)) + Grado3 * (Math.pow(Inter1, 3)) + Grado2 * (Math.pow(Inter1, 2)) + Grado1 * (Math.pow(Inter1, 1)) + GradoC);
        System.out.println("fxa : " + String.format("%." + Decimal + "f", fxa));

        fxb = Math.cos((Grado6 * (Math.pow(Inter2, 6))) + (Grado5 * (Math.pow(Inter2, 5))) + (Grado4 * (Math.pow(Inter2, 4))) + (Grado3 * (Math.pow(Inter2, 3))) + (Grado2 * (Math.pow(Inter2, 2))) + ((Grado1 * (Math.pow(Inter2, 1)))) + GradoC);
        System.out.println("fxb : " + String.format("%." + Decimal + "f", fxb));
        //paso 2
        if (fxa == 0) {//**************
            JOptionPane.showMessageDialog(null, "Se encontro la raiz de fxa", "FELICIDADES", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("El valor es: " + Inter1 + " Su RAIZ: " + String.format("%." + Decimal + "f", fxa));
            return;
        } else if (fxb == 0) {
            JOptionPane.showMessageDialog(null, "Se encontro la raiz de fxB", "FELICIDADES", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("El valor es: " + Inter2 + " Su RAIZ: " + String.format("%." + Decimal + "f", fxb));
            return;
        }//-*********************

        comp = fxa * fxb;
        System.out.println("COMPARACION: " + comp);
        if (comp < 0) {

            //primera aproximscion de la raiz
            xr = (((fxa * Inter2) - (fxb * Inter1)) / (fxa - fxb));//aproximacion -0.083
            System.out.println("xr: " + xr);
            Inter1 = xr;
            do {
                count++;
                System.out.println("------CONTADOR-----: " + count);

                fxa = Math.cos((Grado6 * (Math.pow(Inter1, 6)) + Grado5 * (Math.pow(Inter1, 5)) + Grado4 * (Math.pow(Inter1, 4)) + Grado3 * (Math.pow(Inter1, 3)) + Grado2 * (Math.pow(Inter1, 2)) + Grado1 * (Math.pow(Inter1, 1)) + GradoC));
                System.out.println("fxa dentro de do: " + String.format("%." + Decimal + "f", fxa));//0
                XRNV = XRN;

                //se hace la formula iterativva XRN
                XRN = Inter2 - (((fxb * Inter1) - (fxb * Inter2)) / (fxa - fxb));
                System.out.println("APROXIMACION DE LA RAIZ: " + String.format("%." + Decimal + "f", XRN));//0

                //System.out.println("fxa: " + fxa);
                err = (Math.abs((XRN - XRNV) / XRN)) * 100;
                System.out.println("Error relativo: " + err);
                if (err <= ErrorI) {//ERROR DIGITADO
                    System.out.println("");
                    System.out.println("APROXIMACION DE LA RAIZ: " + String.format("%." + Decimal + "f", XRN));//0
                    System.out.println("tu error final es: " + err);
                    return;
                } else {
                    Inter1 = XRN;
                }
            } while (count <= 100);

        } else {
            JOptionPane.showMessageDialog(this, "NO ES EL INTERVALO CORRECTO. ¿DESEA CONTINUAR?", "UPS!", JOptionPane.YES_NO_OPTION);
            //se aplicara forzar el programa.
            FuerzaCoseno();
            return;
        }

    }

    public void FuerzaCoseno() {

        xr = (((fxa * Inter2) - (fxb * Inter1)) / (fxa - fxb));//aproximacion -0.083
        System.out.println("xr: " + xr);
        do {
            count++;
            Inter1 = xr;//xr corresponde a xa(Inter1) y xa(Inter1) es el nuevo vslor.
            System.out.println("ITERADOR------" + count);
            System.out.println("fxa : " + fxa);
            System.out.println("fxb : " + fxb);
            System.out.println("Error : " + err);
            System.out.println("xr: " + xr);
            System.out.println("xrn: " + xrn);
            //System.out.println("xrn: " + xrn);
            //System.out.println("INTER1 XA: " + Inter1);
            //se sustuye en fxa con el nuevo valor xa

            fxa = Math.cos((Grado6 * (Math.pow(Inter1, 6)) + Grado5 * (Math.pow(Inter1, 5)) + Grado4 * (Math.pow(Inter1, 4)) + Grado3 * (Math.pow(Inter1, 3)) + Grado2 * (Math.pow(Inter1, 2)) + Grado1 * (Math.pow(Inter1, 1)) + GradoC));
            //System.out.println("fxaaaaaaaaaaaa" + fxa);
            fxb = Math.cos((Grado6 * (Math.pow(Inter2, 6))) + (Grado5 * (Math.pow(Inter2, 5))) + (Grado4 * (Math.pow(Inter2, 4))) + (Grado3 * (Math.pow(Inter2, 3))) + (Grado2 * (Math.pow(Inter2, 2))) + ((Grado1 * (Math.pow(Inter2, 1)))) + GradoC);
            xrn = Inter2 - ((fxb * Inter1) - (fxb * Inter2)) / (fxa - fxb);
            //195
            //xrnv = xrn;
            xr = (((fxa * Inter2) - (fxb * Inter1)) / (fxa - fxb));//aproximacion -0.083

            err = (Math.abs((xrn - Inter1) / xrn) * 100);

            if (err <= ErrorI) {
                System.out.println("");
                System.out.println("xrn final: " + xrn);
                System.out.println("Error Final: " + err);
                return;
            } else {

                Inter1 = xrn;
                //System.out.println("Inter1 cambio else: " + Inter1);
                //System.out.println("xrn cambio else: " + xrn);
            }
        } while (count < 100);
    }

    //Tangente
    public void Tangente() {

        System.out.println("Inter1: " + Inter1);
        System.out.println("Inter2: " + Inter2);
        //paso 1
        fxa = Math.tan(Grado6 * (Math.pow(Inter1, 6)) + Grado5 * (Math.pow(Inter1, 5)) + Grado4 * (Math.pow(Inter1, 4)) + Grado3 * (Math.pow(Inter1, 3)) + Grado2 * (Math.pow(Inter1, 2)) + Grado1 * (Math.pow(Inter1, 1)) + GradoC);
        System.out.println("fxa : " + String.format("%." + Decimal + "f", fxa));

        fxb = Math.tan((Grado6 * (Math.pow(Inter2, 6))) + (Grado5 * (Math.pow(Inter2, 5))) + (Grado4 * (Math.pow(Inter2, 4))) + (Grado3 * (Math.pow(Inter2, 3))) + (Grado2 * (Math.pow(Inter2, 2))) + ((Grado1 * (Math.pow(Inter2, 1)))) + GradoC);
        System.out.println("fxb : " + String.format("%." + Decimal + "f", fxb));
        //paso 2
        if (fxa == 0) {//**************
            JOptionPane.showMessageDialog(null, "Se encontro la raiz de fxa", "FELICIDADES", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("El valor es: " + Inter1 + " Su RAIZ: " + String.format("%." + Decimal + "f", fxa));
            return;
        } else if (fxb == 0) {
            JOptionPane.showMessageDialog(null, "Se encontro la raiz de fxB", "FELICIDADES", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("El valor es: " + Inter2 + " Su RAIZ: " + String.format("%." + Decimal + "f", fxb));
            return;
        }//-*********************

        comp = fxa * fxb;
        System.out.println("COMPARACION: " + comp);
        if (comp < 0) {

            //primera aproximscion de la raiz
            xr = (((fxa * Inter2) - (fxb * Inter1)) / (fxa - fxb));//aproximacion -0.083
            System.out.println("xr: " + xr);
            Inter1 = xr;
            do {
                count++;
                System.out.println("------CONTADOR-----: " + count);

                fxa = Math.tan((Grado6 * (Math.pow(Inter1, 6)) + Grado5 * (Math.pow(Inter1, 5)) + Grado4 * (Math.pow(Inter1, 4)) + Grado3 * (Math.pow(Inter1, 3)) + Grado2 * (Math.pow(Inter1, 2)) + Grado1 * (Math.pow(Inter1, 1)) + GradoC));
                System.out.println("fxa dentro de do: " + String.format("%." + Decimal + "f", fxa));//0
                XRNV = XRN;

                //se hace la formula iterativva XRN
                XRN = Inter2 - (((fxb * Inter1) - (fxb * Inter2)) / (fxa - fxb));
                System.out.println("APROXIMACION DE LA RAIZ: " + String.format("%." + Decimal + "f", XRN));//0

                //System.out.println("fxa: " + fxa);
                err = (Math.abs((XRN - XRNV) / XRN)) * 100;
                System.out.println("Error relativo: " + err);
                if (err <= ErrorI) {//ERROR DIGITADO
                    count++;
                    System.out.println("ITERADOR------" + count);
                    System.out.println("RAIZ FINAL: " + XRN);
                    System.out.println("Error Final: " + err);
                    return;
                } else {
                    Inter1 = XRN;
                }
            } while (count <= 100);

        } else {
            JOptionPane.showMessageDialog(this, "NO ES EL INTERVALO CORRECTO. ¿DESEA CONTINUAR?", "UPS!", JOptionPane.YES_NO_OPTION);
            //se aplicara forzar el programa.
            fuerzaTan();
            return;
        }

    }

    public void fuerzaTan() {

        xr = (((fxa * Inter2) - (fxb * Inter1)) / (fxa - fxb));//aproximacion -0.083
        System.out.println("xr: " + xr);
        do {
            count++;
            Inter1 = xr;//xr corresponde a xa(Inter1) y xa(Inter1) es el nuevo vslor.
            System.out.println("ITERADOR------" + count);
            System.out.println("fxa : " + fxa);
            System.out.println("fxb : " + fxb);
            System.out.println("Error : " + err);
            System.out.println("xr: " + xr);
            //System.out.println("xrn: " + xrn);
            //System.out.println("INTER1 XA: " + Inter1);
            //se sustuye en fxa con el nuevo valor xa

            fxa = Math.tan((Grado6 * (Math.pow(Inter1, 6)) + Grado5 * (Math.pow(Inter1, 5)) + Grado4 * (Math.pow(Inter1, 4)) + Grado3 * (Math.pow(Inter1, 3)) + Grado2 * (Math.pow(Inter1, 2)) + Grado1 * (Math.pow(Inter1, 1)) + GradoC));
            //System.out.println("fxaaaaaaaaaaaa" + fxa);
            fxb = Math.tan((Grado6 * (Math.pow(Inter2, 6))) + (Grado5 * (Math.pow(Inter2, 5))) + (Grado4 * (Math.pow(Inter2, 4))) + (Grado3 * (Math.pow(Inter2, 3))) + (Grado2 * (Math.pow(Inter2, 2))) + ((Grado1 * (Math.pow(Inter2, 1)))) + GradoC);
            xrn = Inter2 - ((fxb * Inter1) - (fxb * Inter2)) / (fxa - fxb);
            //195
            //xrnv = xrn;
            xr = (((fxa * Inter2) - (fxb * Inter1)) / (fxa - fxb));//aproximacion -0.083

            err = (Math.abs((xrn - Inter1) / xrn) * 100);

            if (err <= ErrorI) {
                count++;
                System.out.println("ITERADOR------" + count);
                System.out.println("RAIZ FINAL: " + xr);
                System.out.println("Error Final: " + err);
                return;
            } else {
                //195
                Inter1 = xrn;
                //System.out.println("Inter1 cambio else: " + Inter1);
                //System.out.println("xrn cambio else: " + xrn);
            }
        } while (count < 100);
    }

    //Contangente
    public void Contangente() {

        System.out.println("Inter1: " + Inter1);
        System.out.println("Inter2: " + Inter2);
        //paso 1
        fxa = 1 / (Math.tan(Grado6 * (Math.pow(Inter1, 6)) + Grado5 * (Math.pow(Inter1, 5)) + Grado4 * (Math.pow(Inter1, 4)) + Grado3 * (Math.pow(Inter1, 3)) + Grado2 * (Math.pow(Inter1, 2)) + Grado1 * (Math.pow(Inter1, 1)) + GradoC));
        System.out.println("fxa : " + String.format("%." + Decimal + "f", fxa));

        fxb = 1 / (Math.tan((Grado6 * (Math.pow(Inter2, 6))) + (Grado5 * (Math.pow(Inter2, 5))) + (Grado4 * (Math.pow(Inter2, 4))) + (Grado3 * (Math.pow(Inter2, 3))) + (Grado2 * (Math.pow(Inter2, 2))) + ((Grado1 * (Math.pow(Inter2, 1)))) + GradoC));
        System.out.println("fxb : " + String.format("%." + Decimal + "f", fxb));
        //paso 2
        if (fxa == 0) {//**************
            JOptionPane.showMessageDialog(null, "Se encontro la raiz de fxa", "FELICIDADES", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("El valor es: " + Inter1 + " Su RAIZ: " + String.format("%." + Decimal + "f", fxa));
            return;
        } else if (fxb == 0) {
            JOptionPane.showMessageDialog(null, "Se encontro la raiz de fxB", "FELICIDADES", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("El valor es: " + Inter2 + " Su RAIZ: " + String.format("%." + Decimal + "f", fxb));
            return;
        }//-*********************

        comp = fxa * fxb;
        System.out.println("COMPARACION: " + comp);
        if (comp < 0) {

            //primera aproximscion de la raiz
            xr = (((fxa * Inter2) - (fxb * Inter1)) / (fxa - fxb));//aproximacion -0.083
            System.out.println("xr: " + xr);
            Inter1 = xr;
            do {
                count++;
                System.out.println("------CONTADOR-----: " + count);

                fxa = 1 / (Math.tan((Grado6 * (Math.pow(Inter1, 6)) + Grado5 * (Math.pow(Inter1, 5)) + Grado4 * (Math.pow(Inter1, 4)) + Grado3 * (Math.pow(Inter1, 3)) + Grado2 * (Math.pow(Inter1, 2)) + Grado1 * (Math.pow(Inter1, 1)) + GradoC)));
                System.out.println("fxa dentro de do: " + String.format("%." + Decimal + "f", fxa));//0
                XRNV = XRN;

                //se hace la formula iterativva XRN
                XRN = Inter2 - (((fxb * Inter1) - (fxb * Inter2)) / (fxa - fxb));
                System.out.println("APROXIMACION DE LA RAIZ: " + String.format("%." + Decimal + "f", XRN));//0

                //System.out.println("fxa: " + fxa);
                err = (Math.abs((XRN - XRNV) / XRN)) * 100;
                System.out.println("Error relativo: " + err);
                if (err <= ErrorI) {//ERROR DIGITADO
                    count++;
                    System.out.println("ITERADOR------" + count);
                    System.out.println("RAIZ FINAL: " + XRN);
                    System.out.println("Error Final: " + err);
                    return;
                } else {
                    Inter1 = XRN;
                }
            } while (count <= 100);

        } else {
            JOptionPane.showMessageDialog(this, "NO ES EL INTERVALO CORRECTO. ¿DESEA CONTINUAR?", "UPS!", JOptionPane.YES_NO_OPTION);
            //se aplicara forzar el programa.
            FuerzaContangente();
            return;
        }

    }

    public void FuerzaContangente() {

        xr = (((fxa * Inter2) - (fxb * Inter1)) / (fxa - fxb));//aproximacion -0.083
        System.out.println("xr: " + xr);
        do {
            count++;
            Inter1 = xr;//xr corresponde a xa(Inter1) y xa(Inter1) es el nuevo vslor.
            System.out.println("ITERADOR------" + count);
            System.out.println("fxa : " + fxa);
            System.out.println("fxb : " + fxb);
            System.out.println("Error : " + err);
            System.out.println("xr: " + xr);
            //System.out.println("xrn: " + xrn);
            //System.out.println("INTER1 XA: " + Inter1);
            //se sustuye en fxa con el nuevo valor xa

            fxa = 1 / (Math.tan((Grado6 * (Math.pow(Inter1, 6)) + Grado5 * (Math.pow(Inter1, 5)) + Grado4 * (Math.pow(Inter1, 4)) + Grado3 * (Math.pow(Inter1, 3)) + Grado2 * (Math.pow(Inter1, 2)) + Grado1 * (Math.pow(Inter1, 1)) + GradoC)));
            //System.out.println("fxaaaaaaaaaaaa" + fxa);
            fxb = 1 / (Math.tan((Grado6 * (Math.pow(Inter2, 6))) + (Grado5 * (Math.pow(Inter2, 5))) + (Grado4 * (Math.pow(Inter2, 4))) + (Grado3 * (Math.pow(Inter2, 3))) + (Grado2 * (Math.pow(Inter2, 2))) + ((Grado1 * (Math.pow(Inter2, 1)))) + GradoC));
            xrn = Inter2 - ((fxb * Inter1) - (fxb * Inter2)) / (fxa - fxb);
            //195
            //xrnv = xrn;
            xr = (((fxa * Inter2) - (fxb * Inter1)) / (fxa - fxb));//aproximacion -0.083

            err = (Math.abs((xrn - Inter1) / xrn) * 100);

            if (err <= ErrorI) {
                count++;
                System.out.println("ITERADOR------" + count);
                System.out.println("RAIZ FINAL: " + xr);
                System.out.println("Error Final: " + err);
                return;
            } else {
                //195
                Inter1 = xrn;
                //System.out.println("Inter1 cambio else: " + Inter1);
                //System.out.println("xrn cambio else: " + xrn);
            }
        } while (count < 100);
    }

    //Secante
    public void Secante() {

        System.out.println("Inter1: " + Inter1);
        System.out.println("Inter2: " + Inter2);
        //paso 1
        fxa = 1 / (Math.cos(Grado6 * (Math.pow(Inter1, 6)) + Grado5 * (Math.pow(Inter1, 5)) + Grado4 * (Math.pow(Inter1, 4)) + Grado3 * (Math.pow(Inter1, 3)) + Grado2 * (Math.pow(Inter1, 2)) + Grado1 * (Math.pow(Inter1, 1)) + GradoC));
        System.out.println("fxa : " + String.format("%." + Decimal + "f", fxa));

        fxb = 1 / (Math.cos((Grado6 * (Math.pow(Inter2, 6))) + (Grado5 * (Math.pow(Inter2, 5))) + (Grado4 * (Math.pow(Inter2, 4))) + (Grado3 * (Math.pow(Inter2, 3))) + (Grado2 * (Math.pow(Inter2, 2))) + ((Grado1 * (Math.pow(Inter2, 1)))) + GradoC));
        System.out.println("fxb : " + String.format("%." + Decimal + "f", fxb));
        //paso 2
        if (fxa == 0) {//**************
            JOptionPane.showMessageDialog(null, "Se encontro la raiz de fxa", "FELICIDADES", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("El valor es: " + Inter1 + " Su RAIZ: " + String.format("%." + Decimal + "f", fxa));
            return;
        } else if (fxb == 0) {
            JOptionPane.showMessageDialog(null, "Se encontro la raiz de fxB", "FELICIDADES", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("El valor es: " + Inter2 + " Su RAIZ: " + String.format("%." + Decimal + "f", fxb));
            return;
        }//-*********************

        comp = fxa * fxb;
        System.out.println("COMPARACION: " + comp);
        if (comp < 0) {

            //primera aproximscion de la raiz
            xr = (((fxa * Inter2) - (fxb * Inter1)) / (fxa - fxb));//aproximacion -0.083
            System.out.println("xr: " + xr);
            Inter1 = xr;
            do {
                count++;
                System.out.println("------CONTADOR-----: " + count);

                fxa = 1 / (Math.cos((Grado6 * (Math.pow(Inter1, 6)) + Grado5 * (Math.pow(Inter1, 5)) + Grado4 * (Math.pow(Inter1, 4)) + Grado3 * (Math.pow(Inter1, 3)) + Grado2 * (Math.pow(Inter1, 2)) + Grado1 * (Math.pow(Inter1, 1)) + GradoC)));
                System.out.println("fxa dentro de do: " + String.format("%." + Decimal + "f", fxa));//0
                XRNV = XRN;

                //se hace la formula iterativva XRN
                XRN = Inter2 - (((fxb * Inter1) - (fxb * Inter2)) / (fxa - fxb));
                System.out.println("APROXIMACION DE LA RAIZ: " + String.format("%." + Decimal + "f", XRN));//0

                //System.out.println("fxa: " + fxa);
                err = (Math.abs((XRN - XRNV) / XRN)) * 100;
                System.out.println("Error relativo: " + err);
                if (err <= ErrorI) {//ERROR DIGITADO
                    count++;
                    System.out.println("ITERADOR------" + count);
                    System.out.println("RAIZ FINAL: " + XRN);
                    System.out.println("Error Final: " + err);
                    return;
                } else {
                    Inter1 = XRN;
                }
            } while (count <= 100);

        } else {
            JOptionPane.showMessageDialog(this, "NO ES EL INTERVALO CORRECTO. ¿DESEA CONTINUAR?", "UPS!", JOptionPane.YES_NO_OPTION);
            //se aplicara forzar el programa.
            fuerzaSecante();
            return;
        }
    }

    public void fuerzaSecante() {

        xr = (((fxa * Inter2) - (fxb * Inter1)) / (fxa - fxb));//aproximacion -0.083
        System.out.println("xr: " + xr);
        do {
            count++;
            Inter1 = xr;//xr corresponde a xa(Inter1) y xa(Inter1) es el nuevo vslor.
            System.out.println("ITERADOR------" + count);
            System.out.println("fxa : " + fxa);
            System.out.println("fxb : " + fxb);
            System.out.println("Error : " + err);
            System.out.println("xr: " + xr);
            //System.out.println("xrn: " + xrn);
            //System.out.println("INTER1 XA: " + Inter1);
            //se sustuye en fxa con el nuevo valor xa

            fxa = 1 / (Math.cos((Grado6 * (Math.pow(Inter1, 6)) + Grado5 * (Math.pow(Inter1, 5)) + Grado4 * (Math.pow(Inter1, 4)) + Grado3 * (Math.pow(Inter1, 3)) + Grado2 * (Math.pow(Inter1, 2)) + Grado1 * (Math.pow(Inter1, 1)) + GradoC)));
            //System.out.println("fxaaaaaaaaaaaa" + fxa);
            fxb = 1 / (Math.cos((Grado6 * (Math.pow(Inter2, 6))) + (Grado5 * (Math.pow(Inter2, 5))) + (Grado4 * (Math.pow(Inter2, 4))) + (Grado3 * (Math.pow(Inter2, 3))) + (Grado2 * (Math.pow(Inter2, 2))) + ((Grado1 * (Math.pow(Inter2, 1)))) + GradoC));
            xrn = Inter2 - ((fxb * Inter1) - (fxb * Inter2)) / (fxa - fxb);
            //xrnv = xrn;
            xr = (((fxa * Inter2) - (fxb * Inter1)) / (fxa - fxb));//aproximacion -0.083

            err = (Math.abs((xrn - Inter1) / xrn) * 100);

            if (err <= ErrorI) {
                count++;
                System.out.println("ITERADOR------" + count);
                System.out.println("RAIZ FINAL: " + xr);
                System.out.println("Error Final: " + err);
                return;
            } else {
                //195
                Inter1 = xrn;
                //System.out.println("Inter1 cambio else: " + Inter1);
                //System.out.println("xrn cambio else: " + xrn);
            }
        } while (count < 100);
    }

    //secante
    public void Cosecante() {

        System.out.println("Inter1: " + Inter1);
        System.out.println("Inter2: " + Inter2);
        //paso 1
        fxa = 1 / (Math.sin(Grado6 * (Math.pow(Inter1, 6)) + Grado5 * (Math.pow(Inter1, 5)) + Grado4 * (Math.pow(Inter1, 4)) + Grado3 * (Math.pow(Inter1, 3)) + Grado2 * (Math.pow(Inter1, 2)) + Grado1 * (Math.pow(Inter1, 1)) + GradoC));
        System.out.println("fxa : " + String.format("%." + Decimal + "f", fxa));

        fxb = 1 / (Math.sin((Grado6 * (Math.pow(Inter2, 6))) + (Grado5 * (Math.pow(Inter2, 5))) + (Grado4 * (Math.pow(Inter2, 4))) + (Grado3 * (Math.pow(Inter2, 3))) + (Grado2 * (Math.pow(Inter2, 2))) + ((Grado1 * (Math.pow(Inter2, 1)))) + GradoC));
        System.out.println("fxb : " + String.format("%." + Decimal + "f", fxb));
        //paso 2
        if (fxa == 0) {//**************
            JOptionPane.showMessageDialog(null, "Se encontro la raiz de fxa", "FELICIDADES", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("El valor es: " + Inter1 + " Su RAIZ: " + String.format("%." + Decimal + "f", fxa));
            return;
        } else if (fxb == 0) {
            JOptionPane.showMessageDialog(null, "Se encontro la raiz de fxB", "FELICIDADES", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("El valor es: " + Inter2 + " Su RAIZ: " + String.format("%." + Decimal + "f", fxb));
            return;
        }//-*********************

        comp = fxa * fxb;
        System.out.println("COMPARACION: " + comp);
        if (comp < 0) {

            //primera aproximscion de la raiz
            xr = (((fxa * Inter2) - (fxb * Inter1)) / (fxa - fxb));//aproximacion -0.083
            System.out.println("xr: " + xr);
            Inter1 = xr;
            do {
                count++;
                System.out.println("------CONTADOR-----: " + count);

                fxa = 1 / (Math.sin((Grado6 * (Math.pow(Inter1, 6)) + Grado5 * (Math.pow(Inter1, 5)) + Grado4 * (Math.pow(Inter1, 4)) + Grado3 * (Math.pow(Inter1, 3)) + Grado2 * (Math.pow(Inter1, 2)) + Grado1 * (Math.pow(Inter1, 1)) + GradoC)));
                System.out.println("fxa dentro de do: " + String.format("%." + Decimal + "f", fxa));//0
                XRNV = XRN;

                //se hace la formula iterativva XRN
                XRN = Inter2 - (((fxb * Inter1) - (fxb * Inter2)) / (fxa - fxb));
                System.out.println("APROXIMACION DE LA RAIZ: " + String.format("%." + Decimal + "f", XRN));//0

                //System.out.println("fxa: " + fxa);
                err = (Math.abs((XRN - XRNV) / XRN)) * 100;
                System.out.println("Error relativo: " + err);
                if (err <= ErrorI) {//ERROR DIGITADO
                    count++;
                    System.out.println("ITERADOR------" + count);
                    System.out.println("RAIZ FINAL: " + XRN);
                    System.out.println("Error Final: " + err);
                    return;
                } else {
                    Inter1 = XRN;
                }
            } while (count <= 100);

        } else {
            JOptionPane.showMessageDialog(this, "NO ES EL INTERVALO CORRECTO. ¿DESEA CONTINUAR?", "UPS!", JOptionPane.YES_NO_OPTION);
            //se aplicara forzar el programa.
            fuerzaCosecante();
            return;
        }
    }

    public void fuerzaCosecante() {

        xr = (((fxa * Inter2) - (fxb * Inter1)) / (fxa - fxb));//aproximacion -0.083
        System.out.println("xr: " + xr);
        do {
            count++;
            Inter1 = xr;//xr corresponde a xa(Inter1) y xa(Inter1) es el nuevo vslor.
            System.out.println("ITERADOR------" + count);
            System.out.println("fxa : " + fxa);
            System.out.println("fxb : " + fxb);
            System.out.println("Error : " + err);
            System.out.println("xr: " + xr);
            //System.out.println("xrn: " + xrn);
            //System.out.println("INTER1 XA: " + Inter1);
            //se sustuye en fxa con el nuevo valor xa

            fxa = 1 / (Math.sin((Grado6 * (Math.pow(Inter1, 6)) + Grado5 * (Math.pow(Inter1, 5)) + Grado4 * (Math.pow(Inter1, 4)) + Grado3 * (Math.pow(Inter1, 3)) + Grado2 * (Math.pow(Inter1, 2)) + Grado1 * (Math.pow(Inter1, 1)) + GradoC)));
            //System.out.println("fxaaaaaaaaaaaa" + fxa);
            fxb = 1 / (Math.sin((Grado6 * (Math.pow(Inter2, 6))) + (Grado5 * (Math.pow(Inter2, 5))) + (Grado4 * (Math.pow(Inter2, 4))) + (Grado3 * (Math.pow(Inter2, 3))) + (Grado2 * (Math.pow(Inter2, 2))) + ((Grado1 * (Math.pow(Inter2, 1)))) + GradoC));
            xrn = Inter2 - ((fxb * Inter1) - (fxb * Inter2)) / (fxa - fxb);
            //xrnv = xrn;
            xr = (((fxa * Inter2) - (fxb * Inter1)) / (fxa - fxb));//aproximacion -0.083

            err = (Math.abs((xrn - Inter1) / xrn) * 100);

            if (err <= ErrorI) {
                count++;
                System.out.println("ITERADOR------" + count);
                System.out.println("RAIZ FINAL: " + xr);
                System.out.println("Error Final: " + err);
                return;
            } else {
                //195
                Inter1 = xrn;
                //System.out.println("Inter1 cambio else: " + Inter1);
                //System.out.println("xrn cambio else: " + xrn);
            }
        } while (count < 100);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JCheckBox chbxPiRad;
    private javax.swing.JComboBox<String> cmbxTrigonometricas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldDenominador1;
    private javax.swing.JTextField jTextFieldDenominador2;
    private javax.swing.JTextField jTextFieldNumerador1;
    private javax.swing.JTextField jTextFieldNumerador2;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtConstante;
    private javax.swing.JTextField txtDeciamales;
    private javax.swing.JTextField txtError;
    private javax.swing.JTextField txtGrado1;
    private javax.swing.JTextField txtGrado2;
    private javax.swing.JTextField txtGrado3;
    private javax.swing.JTextField txtGrado4;
    private javax.swing.JTextField txtGrado5;
    private javax.swing.JTextField txtGrado6;
    private javax.swing.JTextField txtInter1;
    private javax.swing.JTextField txtInter2;
    // End of variables declaration//GEN-END:variables
}
