package Metodos2do;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import java.math.*;
import java.text.DecimalFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author yetzr
 */
public class reglaFalsa extends javax.swing.JFrame {
    static double comp1 = 0, comp2 = 0, comp3 = 0, aprox=0, aprox2=0, aprox3=0, pm=0, error=0, x=0, y=0, Errori=0, constante=0, Grado1=0, Grado2=0, Grado3=0, Grado4=0, Grado5=0, Grado6=0;
    static boolean salir = false;
    static int iteracion = 1, decimal=0;
    //grados de valor con las que se haran las operaciones

    
    /**
     * Creates new form biseccion
     */
    public reglaFalsa() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtConstante = new javax.swing.JTextField();
        lblConstante = new javax.swing.JLabel();
        txtGrado1 = new javax.swing.JTextField();
        lblGrado1 = new javax.swing.JLabel();
        lblGrado2 = new javax.swing.JLabel();
        txtGrado2 = new javax.swing.JTextField();
        lblGrado3 = new javax.swing.JLabel();
        txtGrado3 = new javax.swing.JTextField();
        lblGrado4 = new javax.swing.JLabel();
        txtGrado4 = new javax.swing.JTextField();
        lblGrado5 = new javax.swing.JLabel();
        txtGrado5 = new javax.swing.JTextField();
        lblGrado6 = new javax.swing.JLabel();
        txtGrado6 = new javax.swing.JTextField();
        lblError = new javax.swing.JLabel();
        txtError = new javax.swing.JTextField();
        lblDecimales = new javax.swing.JLabel();
        txtDecimales = new javax.swing.JTextField();
        btnResolver = new javax.swing.JButton();
        lblIntervalo1 = new javax.swing.JLabel();
        lblIntervalo2 = new javax.swing.JLabel();
        txtIntervalo1 = new javax.swing.JTextField();
        txtIntervalo2 = new javax.swing.JTextField();
        JpanelTabla = new javax.swing.JPanel();
        btnReiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Regla Falsa");
        setMinimumSize(new java.awt.Dimension(650, 500));
        getContentPane().setLayout(null);

        txtConstante.setMaximumSize(null);
        txtConstante.setPreferredSize(new java.awt.Dimension(55, 22));
        txtConstante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConstanteKeyTyped(evt);
            }
        });
        getContentPane().add(txtConstante);
        txtConstante.setBounds(12, 80, 55, 22);

        lblConstante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConstante.setText("Constante");
        lblConstante.setMinimumSize(new java.awt.Dimension(63, 16));
        lblConstante.setPreferredSize(new java.awt.Dimension(63, 16));
        getContentPane().add(lblConstante);
        lblConstante.setBounds(12, 55, 55, 16);

        txtGrado1.setMaximumSize(null);
        txtGrado1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGrado1KeyTyped(evt);
            }
        });
        getContentPane().add(txtGrado1);
        txtGrado1.setBounds(74, 80, 55, 22);

        lblGrado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGrado1.setText("1°Grado");
        lblGrado1.setMinimumSize(new java.awt.Dimension(63, 16));
        lblGrado1.setPreferredSize(new java.awt.Dimension(63, 16));
        getContentPane().add(lblGrado1);
        lblGrado1.setBounds(74, 55, 55, 16);

        lblGrado2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGrado2.setText("2°Grado");
        lblGrado2.setMinimumSize(new java.awt.Dimension(63, 16));
        lblGrado2.setPreferredSize(new java.awt.Dimension(63, 16));
        getContentPane().add(lblGrado2);
        lblGrado2.setBounds(136, 55, 55, 16);

        txtGrado2.setMaximumSize(null);
        txtGrado2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGrado2KeyTyped(evt);
            }
        });
        getContentPane().add(txtGrado2);
        txtGrado2.setBounds(136, 80, 55, 22);

        lblGrado3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGrado3.setText("3°Grado");
        lblGrado3.setMinimumSize(new java.awt.Dimension(63, 16));
        lblGrado3.setPreferredSize(new java.awt.Dimension(63, 16));
        getContentPane().add(lblGrado3);
        lblGrado3.setBounds(198, 55, 55, 16);

        txtGrado3.setMaximumSize(null);
        txtGrado3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGrado3KeyTyped(evt);
            }
        });
        getContentPane().add(txtGrado3);
        txtGrado3.setBounds(198, 80, 55, 22);

        lblGrado4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGrado4.setText("4°Grado");
        lblGrado4.setMinimumSize(new java.awt.Dimension(63, 16));
        lblGrado4.setPreferredSize(new java.awt.Dimension(63, 16));
        getContentPane().add(lblGrado4);
        lblGrado4.setBounds(260, 55, 55, 16);

        txtGrado4.setMaximumSize(null);
        txtGrado4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGrado4KeyTyped(evt);
            }
        });
        getContentPane().add(txtGrado4);
        txtGrado4.setBounds(260, 80, 55, 22);

        lblGrado5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGrado5.setText("5°Grado");
        lblGrado5.setMinimumSize(new java.awt.Dimension(63, 16));
        lblGrado5.setPreferredSize(new java.awt.Dimension(63, 16));
        getContentPane().add(lblGrado5);
        lblGrado5.setBounds(322, 55, 55, 16);

        txtGrado5.setMaximumSize(null);
        txtGrado5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGrado5KeyTyped(evt);
            }
        });
        getContentPane().add(txtGrado5);
        txtGrado5.setBounds(322, 80, 55, 22);

        lblGrado6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGrado6.setText("6°Grado");
        lblGrado6.setMinimumSize(new java.awt.Dimension(63, 16));
        lblGrado6.setPreferredSize(new java.awt.Dimension(63, 16));
        getContentPane().add(lblGrado6);
        lblGrado6.setBounds(390, 55, 55, 16);

        txtGrado6.setMaximumSize(null);
        txtGrado6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGrado6KeyTyped(evt);
            }
        });
        getContentPane().add(txtGrado6);
        txtGrado6.setBounds(390, 80, 55, 22);

        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblError.setText("Error deseado");
        lblError.setMaximumSize(new java.awt.Dimension(55, 22));
        lblError.setMinimumSize(new java.awt.Dimension(55, 22));
        lblError.setName(""); // NOI18N
        getContentPane().add(lblError);
        lblError.setBounds(10, 130, 75, 22);

        txtError.setMaximumSize(new java.awt.Dimension(55, 22));
        txtError.setMinimumSize(new java.awt.Dimension(55, 22));
        txtError.setName(""); // NOI18N
        txtError.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtErrorKeyTyped(evt);
            }
        });
        getContentPane().add(txtError);
        txtError.setBounds(10, 160, 55, 22);

        lblDecimales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDecimales.setText("N°Decimales");
        lblDecimales.setMaximumSize(new java.awt.Dimension(55, 22));
        lblDecimales.setMinimumSize(new java.awt.Dimension(55, 22));
        lblDecimales.setName(""); // NOI18N
        getContentPane().add(lblDecimales);
        lblDecimales.setBounds(100, 130, 75, 22);

        txtDecimales.setMaximumSize(new java.awt.Dimension(55, 22));
        txtDecimales.setMinimumSize(new java.awt.Dimension(55, 22));
        txtDecimales.setName(""); // NOI18N
        txtDecimales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDecimalesKeyTyped(evt);
            }
        });
        getContentPane().add(txtDecimales);
        txtDecimales.setBounds(100, 160, 55, 22);

        btnResolver.setText("Resolver");
        btnResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnResolver);
        btnResolver.setBounds(10, 210, 77, 25);

        lblIntervalo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIntervalo1.setText("Intervalo 1");
        lblIntervalo1.setToolTipText("");
        getContentPane().add(lblIntervalo1);
        lblIntervalo1.setBounds(435, 130, 80, 16);

        lblIntervalo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIntervalo2.setText("Intervalo 2");
        lblIntervalo2.setToolTipText("");
        getContentPane().add(lblIntervalo2);
        lblIntervalo2.setBounds(545, 130, 80, 16);

        txtIntervalo1.setPreferredSize(new java.awt.Dimension(55, 22));
        txtIntervalo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIntervalo1KeyTyped(evt);
            }
        });
        getContentPane().add(txtIntervalo1);
        txtIntervalo1.setBounds(433, 160, 80, 22);

        txtIntervalo2.setPreferredSize(new java.awt.Dimension(55, 22));
        txtIntervalo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIntervalo2KeyTyped(evt);
            }
        });
        getContentPane().add(txtIntervalo2);
        txtIntervalo2.setBounds(543, 160, 80, 22);
        getContentPane().add(JpanelTabla);
        JpanelTabla.setBounds(200, 200, 440, 180);

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnReiniciar);
        btnReiniciar.setBounds(100, 210, 77, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtConstanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConstanteKeyTyped
        digito(evt);
    }//GEN-LAST:event_txtConstanteKeyTyped

    private void txtGrado1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado1KeyTyped
        digito(evt);
    }//GEN-LAST:event_txtGrado1KeyTyped

    private void txtGrado2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado2KeyTyped
        digito(evt);
    }//GEN-LAST:event_txtGrado2KeyTyped

    private void txtGrado3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado3KeyTyped
        digito(evt);
    }//GEN-LAST:event_txtGrado3KeyTyped

    private void txtGrado4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado4KeyTyped
        digito(evt);
    }//GEN-LAST:event_txtGrado4KeyTyped

    private void txtGrado5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado5KeyTyped
        digito(evt);
    }//GEN-LAST:event_txtGrado5KeyTyped

    private void txtGrado6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado6KeyTyped
        digito(evt);
    }//GEN-LAST:event_txtGrado6KeyTyped

    private void txtErrorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtErrorKeyTyped
        digito2(evt);
    }//GEN-LAST:event_txtErrorKeyTyped

    private void txtDecimalesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDecimalesKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtDecimalesKeyTyped

    private void btnResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolverActionPerformed
            
            limpiar();
            DefaultTableModel model = new DefaultTableModel(); 
            JTable table = new JTable(model); 
            // Create a couple of columns 
            model.addColumn("Iteracion"); 
            model.addColumn("Error"); 
            model.addColumn("Punto medio");
            Object[] columns = {"Iteración","Error","Punto medio"};
            model.setColumnIdentifiers(columns);
            table.setModel(model);
            
            JpanelTabla.add(table);
            table.setVisible(true);
            table.setBounds(400, 400, 440, 180);
            table.setLocation(440, 180);
             // Change A JTable Background Color, Font Size, Font Color, Row Height
            
            table.setBackground(Color.LIGHT_GRAY);
            table.setForeground(Color.black);
            Font font = new Font("",0,12);
            table.setFont(font);
            table.setRowHeight(30);
            
             // set the model to the table
            
        
        if(!error(txtConstante) || !error(txtDecimales) || !error(txtError) || !error(txtGrado1) || !error(txtGrado2) || !error(txtGrado3) || !error(txtGrado4) || !error(txtGrado5) || !error(txtGrado6) || !error(txtIntervalo1) || !error(txtIntervalo2))
        {
            JOptionPane.showMessageDialog(this, "Rellene todos los campos.\n Campos vacios con 0.", "Error", JOptionPane.ERROR_MESSAGE);
            return;   
        }
        //parametros
        x=Double.parseDouble(txtIntervalo1.getText());
        y=Double.parseDouble(txtIntervalo2.getText());
        Errori=Double.parseDouble(txtError.getText());
        //grados de valor con las que se haran las operaciones
        decimal=Integer.parseInt(txtDecimales.getText());
        constante=Double.parseDouble(txtConstante.getText());
        Grado1=Double.parseDouble(txtGrado1.getText());
        Grado2=Double.parseDouble(txtGrado2.getText());
        Grado3=Double.parseDouble(txtGrado3.getText());
        Grado4=Double.parseDouble(txtGrado4.getText());
        Grado5=Double.parseDouble(txtGrado5.getText());
        Grado6=Double.parseDouble(txtGrado6.getText());
        
        comp1 = Grado6 * Math.pow(x, 6) + Grado5 * Math.pow(x, 5) + Grado4 * Math.pow(x, 4) + Grado3 * Math.pow(x, 3) + Grado2 * Math.pow(x, 2) + Grado1 * Math.pow(x, 1) + constante;
        comp2 = Grado6 * Math.pow(y, 6) + Grado5 * Math.pow(y, 5) + Grado4 * Math.pow(y, 4) + Grado3 * Math.pow(y, 3) + Grado2 * Math.pow(y, 2) + Grado1 * Math.pow(y, 1) + constante;
        
        aprox = ((comp1*y)-(comp2*x))/(comp1-comp2);
        System.out.println("Multiplicación en el intervalo 1" + comp1);
        System.out.println("Multiplicación en el intervalo 2" + comp2);
        if(comp1==0)
        {
            JOptionPane.showMessageDialog(rootPane, "La función en el intervalo 1 es la raíz", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(comp2==0)
        {
            JOptionPane.showMessageDialog(rootPane, "La función en el intervalo 2 es la raíz", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(aprox>0){
            JOptionPane.showMessageDialog(rootPane, "Los datos del intervalo que ingreso sí contienen la respuesta correcta", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            if(JOptionPane.showConfirmDialog(this, "¿quiere seguir con las comprobaciones?\n Se harán 100 comprobaciones y se arrojará el resultado","aviso",JOptionPane.INFORMATION_MESSAGE)==JOptionPane.NO_OPTION){
                    JOptionPane.showMessageDialog(this, "Saliendo","aviso",JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
        }
        if(aprox<0){
            JOptionPane.showMessageDialog(rootPane, "Los datos del intervalo que ingreso sí contienen la respuesta correcta", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
            double pm =(((comp1*y)-(comp2*x))/(comp1-comp2));
            do{
                x=pm;
                iteracion++;
                System.out.println("iteracion :" + iteracion);
                comp1 = (constante) + (Grado1 * Math.pow(x, 1)) + (Grado2 * Math.pow(x, 2)) + (Grado3 * Math.pow(x, 3)) + (Grado4 * Math.pow(x, 4)) + (Grado5 * Math.pow(x, 5)) + (Grado6 * Math.pow(x, 6));
                comp2 = (constante) + (Grado1 * Math.pow(y, 1)) + (Grado2 * Math.pow(y, 2)) + (Grado3 * Math.pow(y, 3)) + (Grado4 * Math.pow(y, 4)) + (Grado5 * Math.pow(y, 5)) + (Grado6 * Math.pow(y, 6));
                
                pm=y-(((comp2*x)-(comp2*y))/((comp1-comp2)));
                System.out.println(pm);
                error = ((pm - x) / pm) * 100;
                error = Math.abs(error);
                System.out.println(error);
                
                if(error == 0 || error <= Errori || Errori < 0 ){
                        salir=true;
                    }
                if(iteracion == 100){
                        JOptionPane.showMessageDialog(rootPane, "Se alcanzo el máximo de iteraciones\nSe muestra el último resultado", "Aviso", HEIGHT);
                        salir=true;
                    }
            }while (salir == false);
        
    }//GEN-LAST:event_btnResolverActionPerformed

    private void txtIntervalo1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIntervalo1KeyTyped
        digito(evt);
    }//GEN-LAST:event_txtIntervalo1KeyTyped

    private void txtIntervalo2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIntervalo2KeyTyped
        digito(evt);
    }//GEN-LAST:event_txtIntervalo2KeyTyped

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        limpiar();
        txtConstante.setText("");
        txtDecimales.setText("");
        txtError.setText("");
        txtGrado1.setText("");
        txtGrado2.setText("");
        txtGrado3.setText("");
        txtGrado4.setText("");
        txtGrado5.setText("");
        txtGrado6.setText("");
        txtIntervalo1.setText("");
        txtIntervalo2.setText("");
    }//GEN-LAST:event_btnReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reglaFalsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reglaFalsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reglaFalsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reglaFalsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reglaFalsa().setVisible(true);
            }
        });
    }
    
    public static void digito(java.awt.event.KeyEvent evt)
    {
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) && c!='.' && c!='-')
        {
            evt.consume();
        }
    }
    public static void digito2(java.awt.event.KeyEvent evt)
    {
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) && c!='.')
        {
            evt.consume();
        }
    }

     public static boolean error(javax.swing.JTextField t)
     {
        if("".equals(t.getText())) 
        {
            return false;
        }
        return true;
     }
     public static void limpiar()
     {
         salir = false;
            iteracion = 0;
            x = 0;
            y = 0;
            Errori = 0;
            decimal = 0;
            constante = 0;
            Grado1 = 0;
            Grado2 = 0;
            Grado3 = 0;
            Grado4 = 0;
            Grado5 = 0;
            Grado6 = 0;
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpanelTabla;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnResolver;
    private javax.swing.JLabel lblConstante;
    private javax.swing.JLabel lblDecimales;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblGrado1;
    private javax.swing.JLabel lblGrado2;
    private javax.swing.JLabel lblGrado3;
    private javax.swing.JLabel lblGrado4;
    private javax.swing.JLabel lblGrado5;
    private javax.swing.JLabel lblGrado6;
    private javax.swing.JLabel lblIntervalo1;
    private javax.swing.JLabel lblIntervalo2;
    private javax.swing.JTextField txtConstante;
    private javax.swing.JTextField txtDecimales;
    private javax.swing.JTextField txtError;
    private javax.swing.JTextField txtGrado1;
    private javax.swing.JTextField txtGrado2;
    private javax.swing.JTextField txtGrado3;
    private javax.swing.JTextField txtGrado4;
    private javax.swing.JTextField txtGrado5;
    private javax.swing.JTextField txtGrado6;
    private javax.swing.JTextField txtIntervalo1;
    private javax.swing.JTextField txtIntervalo2;
    // End of variables declaration//GEN-END:variables
}

